// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioPhoneNumbersError;
use standard_error::traits::StandardErrorCausesTrait;

impl StandardErrorCausesTrait for TwilioPhoneNumbersError {
    fn causes(&self) -> Option<&'static str> {
        match self {
            TwilioPhoneNumbersError::ErrorCode22225 => Some(r#"The FromBundleSid specified does not exist."#),
            TwilioPhoneNumbersError::ErrorCode22152 => Some(r#"The phone number is inactive or disconnected on the losing carrier and so cannot be ported. "#),
            TwilioPhoneNumbersError::ErrorCode22155 => Some(r#"An invalid or no PIN for this phone number was submitted as part of the port in request."#),
            TwilioPhoneNumbersError::ErrorCode22205 => Some(r#"The object_sid may be malformed or belonging to a different account."#),
            TwilioPhoneNumbersError::ErrorCode22212 => Some(r#"The End-User Type is malformed or is not an acceptable value."#),
            TwilioPhoneNumbersError::ErrorCode22112 => None,
            TwilioPhoneNumbersError::ErrorCode18056 => Some(r#"The work email of the Authorized Representative was not provided."#),
            TwilioPhoneNumbersError::ErrorCode22213 => Some(r#"The Number Type is malformed or is not an acceptable value."#),
            TwilioPhoneNumbersError::ErrorCode22210 => Some(r#"Either the Type string was malformed or the Supporting Document Type name does not exist."#),
            TwilioPhoneNumbersError::ErrorCode18060 => Some(r#"Missed uploading or upload failure"#),
            TwilioPhoneNumbersError::ErrorCode18605 => Some(r#"Unable to verify Authorized representative #2’s identity or their affiliation with the business."#),
            TwilioPhoneNumbersError::ErrorCode18609 => Some(r#"The submitted business registration authority does not meet the eligibility requirements for the US Voice Integrity/CNAM trust product."#),
            TwilioPhoneNumbersError::ErrorCode22171 => Some(r#"There are missing required fields for the country your phone numbers are related to."#),
            TwilioPhoneNumbersError::ErrorCode22122 => None,
            TwilioPhoneNumbersError::ErrorCode21628 => None,
            TwilioPhoneNumbersError::ErrorCode22118 => None,
            TwilioPhoneNumbersError::ErrorCode22217 => Some(r#"The Regulation requires a Supporting Document field which is missing from your Regulatory Bundle."#),
            TwilioPhoneNumbersError::ErrorCode18008 => Some(r#"The name on the Proof of Identity document does not match what's submitted in the first name / last name fields."#),
            TwilioPhoneNumbersError::ErrorCode22133 => Some(r#"The phone number cannot be ported using the Twilio porting API. "#),
            TwilioPhoneNumbersError::ErrorCode22130 => Some(r#"Phone number is in a country or rate center that is not supported by Twilio"#),
            TwilioPhoneNumbersError::ErrorCode22114 => None,
            TwilioPhoneNumbersError::ErrorCode22111 => None,
            TwilioPhoneNumbersError::ErrorCode22151 => Some(r#"A carrier may place a restriction on a phone number to prevent porting for many reasons, common ones include service freezes to prevent unauthorized transfers or billing problems."#),
            TwilioPhoneNumbersError::ErrorCode21650 => None,
            TwilioPhoneNumbersError::ErrorCode18036 => Some(r#"You may have missed to input the required information."#),
            TwilioPhoneNumbersError::ErrorCode18608 => Some(r#"You already copied."#),
            TwilioPhoneNumbersError::ErrorCode18053 => Some(r#"The business name does not match the website SSL certificate, or the website URL."#),
            TwilioPhoneNumbersError::ErrorCode22153 => Some(r#"The name of the Authorized Representative submitted in the port in request does not the losing carrier's information. "#),
            TwilioPhoneNumbersError::ErrorCode18051 => Some(r#"One of the inputs (information or documents) you provided has issues."#),
            TwilioPhoneNumbersError::ErrorCode18604 => Some(r#"Unable to verify Authorized representative #1’s identity or their affiliation with the business."#),
            TwilioPhoneNumbersError::ErrorCode22401 => Some(r#"The feature is not supported within the region."#),
            TwilioPhoneNumbersError::ErrorCode22200 => Some(r#"The End-User Type or Number Type is malformed or is not an acceptable value."#),
            TwilioPhoneNumbersError::ErrorCode18606 => Some(r#"The domain of the email address you provided doesn't match the website domain."#),
            TwilioPhoneNumbersError::ErrorCode22102 => Some(r#"* The phone number provided is formatted incorrectly.

* The phone number provided includes a non-existent country code, area code or exchange."#),
            TwilioPhoneNumbersError::ErrorCode18607 => Some(r#"The customer profile is not eligible to be copied"#),
            TwilioPhoneNumbersError::ErrorCode18005 => Some(r#"You may have missed sharing the required information."#),
            TwilioPhoneNumbersError::ErrorCode18017 => Some(r#"The identity document that you submitted for address document does not have the address"#),
            TwilioPhoneNumbersError::ErrorCode21648 => Some(r#"The Regulatory Bundle cannot be deleted due to an active number assignment.a"#),
            TwilioPhoneNumbersError::ErrorCode18052 => Some(r#"The Authorized Representative's age is under 18 years, which is considered underage to use Twilio's products."#),
            TwilioPhoneNumbersError::ErrorCode22402 => Some(r#"Certain Phone Number operations are not permitted within this Region such as restore, transfer, emergency services, and release."#),
            TwilioPhoneNumbersError::ErrorCode21630 => None,
            TwilioPhoneNumbersError::ErrorCode21449 => None,
            TwilioPhoneNumbersError::ErrorCode18055 => Some(r#"The email format is incorrect or contains errors."#),
            TwilioPhoneNumbersError::ErrorCode22215 => Some(r#"The Regulation requires an End-User field which is missing from your Regulatory Bundle."#),
            TwilioPhoneNumbersError::ErrorCode18054 => Some(r#"The phone number format is incorrect or or contains errors."#),
            TwilioPhoneNumbersError::ErrorCode18603 => Some(r#"The address is not found in an authoritative address database."#),
            TwilioPhoneNumbersError::ErrorCode18058 => Some(r#"An Authorized Representative's Tax ID is missing."#),
            TwilioPhoneNumbersError::ErrorCode18012 => Some(r#"- You may have submitted an international address.
- Your address is not a valid address."#),
            TwilioPhoneNumbersError::ErrorCode22403 => Some(r#"Certain Phone Number operations are not permitted within this Region emergency services"#),
            TwilioPhoneNumbersError::ErrorCode22400 => Some(r#"Phone Number linked to Active Route Configuration."#),
            TwilioPhoneNumbersError::ErrorCode18061 => Some(r#"- There is a mistake in the registration number, either on the document or in the bundle information
- Your registration may have expired
- Registration database might have a technical glitch"#),
            TwilioPhoneNumbersError::ErrorCode18024 => Some(r#"The file type does not match the file content or the file corrupt/invalid."#),
            TwilioPhoneNumbersError::ErrorCode18602 => Some(r#"You may have provided an inaccurate business ID or the Business ID is invalid / expired."#),
            TwilioPhoneNumbersError::ErrorCode22224 => Some(r#"The status is either not eligible as all Bundles need to be in a twilio-approved state or the destination Bundle is not a Copy of the source Bundle."#),
            TwilioPhoneNumbersError::ErrorCode22207 => Some(r#"The JSON was invalid."#),
            TwilioPhoneNumbersError::ErrorCode22230 => Some(r#"The Address linked to the Regulatory Bundle was deleted."#),
            TwilioPhoneNumbersError::ErrorCode22159 => Some(r#"The most likely case here is that the phone number uses services on the losing carrier that prevent it from being ported. For example, in Japan both rental phone numbers & public phone numbers cannot be ported.

In rare cases, the number may have been incorrectly typed by Twilio's Portability API and the requested number is not actually portable."#),
            TwilioPhoneNumbersError::ErrorCode22204 => Some(r#"Status update and a property update are in the same request"#),
            TwilioPhoneNumbersError::ErrorCode22113 => None,
            TwilioPhoneNumbersError::ErrorCode22203 => Some(r#"Bundle status is not a valid option from the enum values"#),
            TwilioPhoneNumbersError::ErrorCode18099 => Some(r#"The API request to submit this bundle set the IsTest parameter to true."#),
            TwilioPhoneNumbersError::ErrorCode18022 => Some(r#"The address document contains a date that is in the past."#),
            TwilioPhoneNumbersError::ErrorCode22214 => Some(r#"The Regulation requires an end-user which is missing from the regulatory bundle you are attempting to evaluate."#),
            TwilioPhoneNumbersError::ErrorCode22209 => Some(r#"The status enum may be malformed or incorrect."#),
            TwilioPhoneNumbersError::ErrorCode22404 => Some(r#"The profile you are trying to create/update is a Starter profile. See [New Requirements for A2P 10DLC Registrations](https://www.twilio.com/blog/new-requirements-for-a2p-10dlc-registrations) for more info."#),
            TwilioPhoneNumbersError::ErrorCode22119 => None,
            TwilioPhoneNumbersError::ErrorCode18038 => Some(r#"You may have attached the wrong document or shared inaccurate information."#),
            TwilioPhoneNumbersError::ErrorCode22105 => None,
            TwilioPhoneNumbersError::ErrorCode22117 => None,
            TwilioPhoneNumbersError::ErrorCode22108 => None,
            TwilioPhoneNumbersError::ErrorCode10002 => Some(r#"You attempted to use a premium feature with a trial account."#),
            TwilioPhoneNumbersError::ErrorCode18004 => Some(r#"Uploading a document with obscured or redacted information."#),
            TwilioPhoneNumbersError::ErrorCode18014 => Some(r#"The submitted address does not meet our requirements."#),
            TwilioPhoneNumbersError::ErrorCode18001 => Some(r#"The document you have uploaded does not match our acceptable documentation for the Regulatory Requirements."#),
            TwilioPhoneNumbersError::ErrorCode22222 => Some(r#"You sent a *POST* request to update the Emergency Status"#),
            TwilioPhoneNumbersError::ErrorCode18011 => Some(r#"The business name and registration information do not align with the local company register or excerpt from the commercial register."#),
            TwilioPhoneNumbersError::ErrorCode22218 => Some(r#"The Regulation requires the fields on the Supporting Document and End-User to match."#),
            TwilioPhoneNumbersError::ErrorCode22208 => Some(r#"The Supporting Documents status cannot have both the status and the attributes in the same update request."#),
            TwilioPhoneNumbersError::ErrorCode22120 => None,
            TwilioPhoneNumbersError::ErrorCode22206 => Some(r#"The SID belongs to a different object group that is not allowed to be assigned as an item to a Bundle."#),
            TwilioPhoneNumbersError::ErrorCode22135 => Some(r#"Internal error determining the portability of this number, please try again"#),
            TwilioPhoneNumbersError::ErrorCode22500 => Some(r#"The Twilio phone number is configured for the 2008-08-01 API"#),
            TwilioPhoneNumbersError::ErrorCode18007 => Some(r#"Your uploaded proof of Identity does not have both sides."#),
            TwilioPhoneNumbersError::ErrorCode22121 => None,
            TwilioPhoneNumbersError::ErrorCode22211 => Some(r#"The FriendlyName is missing from the POST LIST request to create a new Supporting Document."#),
            TwilioPhoneNumbersError::ErrorCode22202 => Some(r#"The regulation sid or phone number country and type are missing from the request."#),
            TwilioPhoneNumbersError::ErrorCode22115 => None,
            TwilioPhoneNumbersError::ErrorCode18010 => Some(r#"The submitted business registration number does not align with the local company register or excerpt from the commercial register."#),
            TwilioPhoneNumbersError::ErrorCode22170 => Some(r#"The Bundle SID does not exist or is not approved yet."#),
            TwilioPhoneNumbersError::ErrorCode22158 => Some(r#"The requested target port date was rejected by the losing carrier. This can happen for a lot of reasons, some common ones include: 
- If the date is on a public holiday
- If the date is on a scheduled maintenance window of the losing carrier"#),
            TwilioPhoneNumbersError::ErrorCode22157 => Some(r#"The subscription right provided as part of the porting request was not accepted by NTT. Certain NTT plans only allow one subscription right, see the solution section for which one you should use. "#),
            TwilioPhoneNumbersError::ErrorCode18020 => Some(r#"The authorized representative is not on the business registration."#),
            TwilioPhoneNumbersError::ErrorCode22136 => Some(r#"Phone number already exists in one of your accounts or is currently being ported into one of your Twilio accounts."#),
            TwilioPhoneNumbersError::ErrorCode22104 => None,
            TwilioPhoneNumbersError::ErrorCode22106 => None,
            TwilioPhoneNumbersError::ErrorCode18002 => Some(r#"Blur or bad quality image uploaded."#),
            TwilioPhoneNumbersError::ErrorCode18018 => Some(r#"PO Box address is not acceptable."#),
            TwilioPhoneNumbersError::ErrorCode22221 => Some(r#"From number does not have a registered emergency address when an emergency call is made."#),
            TwilioPhoneNumbersError::ErrorCode21631 => Some(r#"- No address was provided 
- No address was that satisfies the locality requirement for this phone number type.
- Depending on the country and number type, this may be an address in the same country or same geographic area as the number being purchased."#),
            TwilioPhoneNumbersError::ErrorCode21615 => Some(r#"- No address on your account or subaccount that satisfies the locality requirement. Depending on the country, this can be either same country or same geographic area as the number being purchased."#),
            TwilioPhoneNumbersError::ErrorCode18003 => Some(r#"The Supporting Document you uploaded has expired or it does not show an expiration date."#),
            TwilioPhoneNumbersError::ErrorCode18062 => Some(r#"The status of your entity provided in the business details is listed as inactive in your local business registry."#),
            TwilioPhoneNumbersError::ErrorCode22132 => Some(r#"Phone number already exists on another Twilio account. "#),
            TwilioPhoneNumbersError::ErrorCode22101 => None,
            TwilioPhoneNumbersError::ErrorCode22201 => Some(r#"The regulation sid may be misspelled or belong to another account."#),
            TwilioPhoneNumbersError::ErrorCode22100 => None,
            TwilioPhoneNumbersError::ErrorCode22150 => Some(r#"There was an error during the port in process."#),
            TwilioPhoneNumbersError::ErrorCode22173 => Some(r#"Given Address SID does not exist for your account or is invalid."#),
            TwilioPhoneNumbersError::ErrorCode22103 => None,
            TwilioPhoneNumbersError::ErrorCode18009 => Some(r#"You may have uploaded a wrong document."#),
            TwilioPhoneNumbersError::ErrorCode22131 => Some(r#"Phone number already exists on your Twilio account or is currently being ported into your Twilio account"#),
            TwilioPhoneNumbersError::ErrorCode22109 => None,
            TwilioPhoneNumbersError::ErrorCode22156 => Some(r#"The Account Number submitted for the port in request does not match the losing carrier's information. "#),
            TwilioPhoneNumbersError::ErrorCode21645 => Some(r#"The Supporting Document cannot be deleted as it is an active item assignment in one or more Regulatory Bundles."#),
            TwilioPhoneNumbersError::ErrorCode21651 => None,
            TwilioPhoneNumbersError::ErrorCode18015 => Some(r#"The submitted emergency address does not meet our requirements."#),
            TwilioPhoneNumbersError::ErrorCode18023 => Some(r#"The status of your entity provided in the Business Document is listed as inactive in your local business registry."#),
            TwilioPhoneNumbersError::ErrorCode22199 => Some(r#"Performing an Action that Requires a Configuration in Region in Question"#),
            TwilioPhoneNumbersError::ErrorCode21649 => Some(r#"- No Bundle was provided
- No Bundle was that satisfies the locality requirement for this phone number type
- Depending on the country, number type, and end-user type, the regulations will be different compared to other phone numbers"#),
            TwilioPhoneNumbersError::ErrorCode22116 => None,
            TwilioPhoneNumbersError::ErrorCode22350 => Some(r#"The Phone Number is being ported out of Twilio."#),
            TwilioPhoneNumbersError::ErrorCode22110 => None,
            TwilioPhoneNumbersError::ErrorCode18013 => Some(r#"- You may have submitted an international address.                                                               - Your address is not a valid address."#),
            TwilioPhoneNumbersError::ErrorCode18037 => Some(r#"You may have missed sharing the required information."#),
            TwilioPhoneNumbersError::ErrorCode22172 => Some(r#"There are phone numbers in the port in request from multiple countries.

There are phone numbers in the port in request that are not in E.164 format and so the country cannot be identified. "#),
            TwilioPhoneNumbersError::ErrorCode21646 => Some(r#"The Supporting Document is in a non-deletable status (PENDING_REVIEW)."#),
            TwilioPhoneNumbersError::ErrorCode18021 => Some(r#"The name on the Proof of Address document does not match what's submitted in the first name / last name fields. Please ensure the document and field information match."#),
            TwilioPhoneNumbersError::ErrorCode22216 => Some(r#"The Regulation requires a Supporting Document which is missing from your Regulatory Bundle."#),
            TwilioPhoneNumbersError::ErrorCode22123 => None,
            TwilioPhoneNumbersError::ErrorCode22154 => Some(r#"The address submitted in the port in request does not match the losing carrier's information for this phone number. "#),
            TwilioPhoneNumbersError::ErrorCode22228 => Some(r#"Incompatible Regulation requirements."#),
            TwilioPhoneNumbersError::ErrorCode21629 => None,
            TwilioPhoneNumbersError::ErrorCode18016 => Some(r#"There may be a typo when submitting the address information."#),
            TwilioPhoneNumbersError::ErrorCode18050 => Some(r#"One or more of your Supporting Documents has been reviewed and was found to have issues."#),
            TwilioPhoneNumbersError::ErrorCode22107 => None,
            TwilioPhoneNumbersError::ErrorCode18601 => Some(r#"The business name does not match the website SSL certificate, or the website URL"#),
            TwilioPhoneNumbersError::ErrorCode22300 => Some(r#"Twilio Compliance has temporarily restricted the account from provisioning new long code phone numbers."#),
            TwilioPhoneNumbersError::ErrorCode22229 => Some(r#"The Address in the Bundle Copy must be the same as in the destination Bundle and cannot be removed."#),
            TwilioPhoneNumbersError::ErrorCode18610 => Some(r#"The Address linked to the Customer Profile or Trust Product was deleted."#),
            TwilioPhoneNumbersError::ErrorCode18059 => Some(r#"- Missing government-issued photo ID
- Invalid Photo ID (ex: expired or incorrect name)"#),
            TwilioPhoneNumbersError::ErrorCode180017 => Some(r#"- You may have submitted an international address.
- Your address is not a valid address."#),
            TwilioPhoneNumbersError::ErrorCode18006 => Some(r#"The information you shared does not match the supporting document."#),
            TwilioPhoneNumbersError::ErrorCode21647 => Some(r#"Regulatory Bundle is in a non-deletable status."#),
            TwilioPhoneNumbersError::ErrorCode22219 => Some(r#"The Regulation requires an Address to be assigned to a Supporting Document in the Regulatory Bundle."#),
            TwilioPhoneNumbersError::ErrorCode21644 => Some(r#"The End User cannot be deleted due to one or more active assignments to a Bundle"#),
            TwilioPhoneNumbersError::ErrorCode18019 => Some(r#"We could not verify the identity of the Authorized Representative."#),
            TwilioPhoneNumbersError::ErrorCode18039 => Some(r#"x"#),
            TwilioPhoneNumbersError::ErrorCode18057 => Some(r#"There was an issue verifying the identity of the authorized representative. "#),
            TwilioPhoneNumbersError::ErrorCode22226 => Some(r#"The same FromBundleSid is being used in both the URI and the From Bundle."#)
        }
    }
}
