// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioNotificationsError;
use standard_error::traits::StandardErrorMessageTrait;
use std::borrow::Cow;

impl StandardErrorMessageTrait for TwilioNotificationsError {
    fn message(&self) -> Cow<'static, str> {
        match self {
            TwilioNotificationsError::ErrorCode52108 => r#"GCM/FCM device message rate exceeded"#.into(),
            TwilioNotificationsError::ErrorCode52202 => r#"Facebook page is not connected to Twilio"#.into(),
            TwilioNotificationsError::ErrorCode52052 => r#"Client connection not created or closed"#.into(),
            TwilioNotificationsError::ErrorCode52211 => r#"Too many Alexa notifications"#.into(),
            TwilioNotificationsError::ErrorCode52102 => r#"Invalid GCM/FCM registration token"#.into(),
            TwilioNotificationsError::ErrorCode52143 => r#"The push notification was rejected by APNs"#.into(),
            TwilioNotificationsError::ErrorCode52171 => r#"Webhook Credentials request signature was not verified"#.into(),
            TwilioNotificationsError::ErrorCode52131 => r#"Invalid APNs credentials"#.into(),
            TwilioNotificationsError::ErrorCode52133 => r#"Invalid APNs device token size"#.into(),
            TwilioNotificationsError::ErrorCode52163 => r#"Incorrect URL used to retrieve Webhook Credentials"#.into(),
            TwilioNotificationsError::ErrorCode52162 => r#"Credentials do not belong to used account"#.into(),
            TwilioNotificationsError::ErrorCode52103 => r#"GCM/FCM client uninstalled or turned off notifications"#.into(),
            TwilioNotificationsError::ErrorCode52164 => r#"No Credentials found for the supplied Binding Type"#.into(),
            TwilioNotificationsError::ErrorCode52137 => r#"Invalid size of subject in APNs certificate"#.into(),
            TwilioNotificationsError::ErrorCode52145 => r#"Failed to authenticate with APNs"#.into(),
            TwilioNotificationsError::ErrorCode52001 => r#"Invalid destination binding"#.into(),
            TwilioNotificationsError::ErrorCode52109 => r#"GCM/FCM unauthorized error"#.into(),
            TwilioNotificationsError::ErrorCode52172 => r#"Unexpected Binding Type used for Webhook Credentials request"#.into(),
            TwilioNotificationsError::ErrorCode52104 => r#"Mismatched GCM/FCM sender ID"#.into(),
            TwilioNotificationsError::ErrorCode52071 => r#"Internal error when sending notification via mqtt client connection"#.into(),
            TwilioNotificationsError::ErrorCode52105 => r#"Invalid GCM/FCM package name"#.into(),
            TwilioNotificationsError::ErrorCode52213 => r#"Invalid Alexa user ID"#.into(),
            TwilioNotificationsError::ErrorCode52167 => r#"Invalid Webhook Credentials response"#.into(),
            TwilioNotificationsError::ErrorCode52214 => r#"Alexa skill is not connected to Twilio"#.into(),
            TwilioNotificationsError::ErrorCode52304 => r#"User already exists"#.into(),
            TwilioNotificationsError::ErrorCode52140 => r#"Unknown APNs error"#.into(),
            TwilioNotificationsError::ErrorCode52215 => r#"Missing Title parameter for Alexa"#.into(),
            TwilioNotificationsError::ErrorCode52182 => r#"Messaging Service not specified"#.into(),
            TwilioNotificationsError::ErrorCode52149 => r#"Invalid APNs provider token used"#.into(),
            TwilioNotificationsError::ErrorCode52305 => r#"User already belongs to the segment"#.into(),
            TwilioNotificationsError::ErrorCode52181 => r#"Too many SMS notification requests"#.into(),
            TwilioNotificationsError::ErrorCode52144 => r#"APNs experienced an internal error"#.into(),
            TwilioNotificationsError::ErrorCode52166 => r#"Webhook Credentials endpoint responded with Internal Error"#.into(),
            TwilioNotificationsError::ErrorCode52309 => r#"Channel provider replied with an error"#.into(),
            TwilioNotificationsError::ErrorCode52401 => r#"Too many notification log events "#.into(),
            TwilioNotificationsError::ErrorCode52203 => r#"Missing body for Facebook Messenger delivery attempt"#.into(),
            TwilioNotificationsError::ErrorCode52165 => r#"No Credentials found for the supplied Identifier"#.into(),
            TwilioNotificationsError::ErrorCode52135 => r#"Missing subject in APNs certificate"#.into(),
            TwilioNotificationsError::ErrorCode52107 => r#"Invalid custom key for GCM/FCM"#.into(),
            TwilioNotificationsError::ErrorCode52072 => r#"Client mqtt connection not created or closed"#.into(),
            TwilioNotificationsError::ErrorCode52111 => r#"GCM/FCM unknown error"#.into(),
            TwilioNotificationsError::ErrorCode52307 => r#"No users with provided segments"#.into(),
            TwilioNotificationsError::ErrorCode52000 => r#"Internal notification error"#.into(),
            TwilioNotificationsError::ErrorCode52306 => r#"Cannot delete User resource with Bindings"#.into(),
            TwilioNotificationsError::ErrorCode52136 => r#"Missing payload for APNs delivery"#.into(),
            TwilioNotificationsError::ErrorCode52051 => r#"Internal error when sending notification via client connection"#.into(),
            TwilioNotificationsError::ErrorCode52174 => r#"Unexpected error response received for Webhook Credentials request"#.into(),
            TwilioNotificationsError::ErrorCode52302 => r#"Too many recipients"#.into(),
            TwilioNotificationsError::ErrorCode52138 => r#"APNs payload too large"#.into(),
            TwilioNotificationsError::ErrorCode52170 => r#"Too many Webhook Credential requests"#.into(),
            TwilioNotificationsError::ErrorCode52141 => r#"The provided APNs device token has been unregistered"#.into(),
            TwilioNotificationsError::ErrorCode52161 => r#"Empty Credentials"#.into(),
            TwilioNotificationsError::ErrorCode52301 => r#"Resulted destination list for requested parameters is empty"#.into(),
            TwilioNotificationsError::ErrorCode52142 => r#"The provided APNs device token is not correct"#.into(),
            TwilioNotificationsError::ErrorCode52303 => r#"Concurrent User update"#.into(),
            TwilioNotificationsError::ErrorCode52148 => r#"Expired APNs provider token used"#.into(),
            TwilioNotificationsError::ErrorCode52212 => r#"Missing Alexa skill ID"#.into(),
            TwilioNotificationsError::ErrorCode52003 => r#"Invalid Credential Type"#.into(),
            TwilioNotificationsError::ErrorCode52168 => r#"Webhook Credentials request timed out"#.into(),
            TwilioNotificationsError::ErrorCode52147 => r#"Too many APNs provider token updates"#.into(),
            TwilioNotificationsError::ErrorCode52002 => r#"Invalid Credential Sid"#.into(),
            TwilioNotificationsError::ErrorCode52139 => r#"APN service shutdown"#.into(),
            TwilioNotificationsError::ErrorCode52101 => r#"Invalid GCM Api Key or FCM Secret"#.into(),
            TwilioNotificationsError::ErrorCode52173 => r#"Unexpected Identifier used for Webhook Credentials request"#.into(),
            TwilioNotificationsError::ErrorCode52106 => r#"Notification too large for GCM/FCM"#.into(),
            TwilioNotificationsError::ErrorCode52110 => r#"GCM/FCM service unavailable"#.into(),
            TwilioNotificationsError::ErrorCode52201 => r#"Too many Facebook messenger notification requests"#.into(),
            TwilioNotificationsError::ErrorCode52134 => r#"Invalid APNs device token"#.into()
        }
    }
}
