// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioProgrammableVideoError;
use standard_error::traits::StandardErrorMessageTrait;
use std::borrow::Cow;

impl StandardErrorMessageTrait for TwilioProgrammableVideoError {
    fn message(&self) -> Cow<'static, str> {
        match self {
            TwilioProgrammableVideoError::ErrorCode53628 => r#"Room recordings deleted"#.into(),
            TwilioProgrammableVideoError::ErrorCode53405 => r#"Media connection failed or Media activity ceased"#.into(),
            TwilioProgrammableVideoError::ErrorCode53000 => r#"Signaling connection error"#.into(),
            TwilioProgrammableVideoError::ErrorCode53203 => r#"The maximum number of published tracks allowed in the Room at the same time has been reached"#.into(),
            TwilioProgrammableVideoError::ErrorCode53112 => r#"Status is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53102 => r#"Room name contains invalid characters"#.into(),
            TwilioProgrammableVideoError::ErrorCode53104 => r#"Unable to connect to Room"#.into(),
            TwilioProgrammableVideoError::ErrorCode53408 => r#"ICE connection restart was attempted, but it is not allowed"#.into(),
            TwilioProgrammableVideoError::ErrorCode53106 => r#"Room not found"#.into(),
            TwilioProgrammableVideoError::ErrorCode53616 => r#"Deleted a recording with custom configuration as time for retries was depleted"#.into(),
            TwilioProgrammableVideoError::ErrorCode53301 => r#"Track name is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53300 => r#"Track is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53601 => r#"AWS credentials for recording upload are invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53620 => r#"Invalid URL for external S3 bucket in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53627 => r#"Internal failure when updating the composition resource"#.into(),
            TwilioProgrammableVideoError::ErrorCode53215 => r#"Invalid Subscribe Rule(s)"#.into(),
            TwilioProgrammableVideoError::ErrorCode53204 => r#"Participant not found"#.into(),
            TwilioProgrammableVideoError::ErrorCode53621 => r#"Invalid AWS credentials to access external S3 bucket in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53617 => r#"Internal failure when bulk deleting compositions from your account"#.into(),
            TwilioProgrammableVideoError::ErrorCode53208 => r#"Participant's bandwidth profile configuration is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53205 => r#"Participant disconnected because of duplicate identity"#.into(),
            TwilioProgrammableVideoError::ErrorCode53109 => r#"Timeout is out of range"#.into(),
            TwilioProgrammableVideoError::ErrorCode53661 => r#"StatusCallbackMethod is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53120 => r#" Invalid Recording Rule(s)"#.into(),
            TwilioProgrammableVideoError::ErrorCode53006 => r#"Video server is busy"#.into(),
            TwilioProgrammableVideoError::ErrorCode53002 => r#"Signaling connection timed out"#.into(),
            TwilioProgrammableVideoError::ErrorCode53207 => r#"MaxPublishedTracks is out of range"#.into(),
            TwilioProgrammableVideoError::ErrorCode53113 => r#"Room creation failed"#.into(),
            TwilioProgrammableVideoError::ErrorCode53632 => r#"Failed to enqueue a room composition"#.into(),
            TwilioProgrammableVideoError::ErrorCode53103 => r#" Unable to create Room"#.into(),
            TwilioProgrammableVideoError::ErrorCode53668 => r#"Public key credentials for media tracks encryption could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53001 => r#"Signaling connection disconnected"#.into(),
            TwilioProgrammableVideoError::ErrorCode53206 => r#"The Participant concurrency quota was exceeded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53123 => r#"MaxParticipantDuration is out of range"#.into(),
            TwilioProgrammableVideoError::ErrorCode53626 => r#"Internal failure while processing media composition"#.into(),
            TwilioProgrammableVideoError::ErrorCode53664 => r#"Invalid URL for external S3 bucket in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53202 => r#"Participant identity contains invalid characters"#.into(),
            TwilioProgrammableVideoError::ErrorCode53304 => r#"Track name is duplicated"#.into(),
            TwilioProgrammableVideoError::ErrorCode53622 => r#"Invalid public key for media tracks encryption in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53669 => r#"Access denied to external S3 bucket configured in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53217 => r#"maxAudioTracks or maxVideoTracks configuration is out of range"#.into(),
            TwilioProgrammableVideoError::ErrorCode53501 => r#"Unable to acquire TURN credentials"#.into(),
            TwilioProgrammableVideoError::ErrorCode53603 => r#"Internal failure while processing a recording"#.into(),
            TwilioProgrammableVideoError::ErrorCode53110 => r#"StatusCallbackMethod is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53500 => r#"Unable to acquire configuration"#.into(),
            TwilioProgrammableVideoError::ErrorCode53663 => r#"Internal failure when bulk deleting recordings from your account"#.into(),
            TwilioProgrammableVideoError::ErrorCode53662 => r#"StatusCallback is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53605 => r#"Internal failure when retrieving your account's recording settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53200 => r#"Participant identity is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53630 => r#"Empty track list for composition"#.into(),
            TwilioProgrammableVideoError::ErrorCode53107 => r#"MaxParticipants is out of range"#.into(),
            TwilioProgrammableVideoError::ErrorCode53633 => r#"Composition is too large"#.into(),
            TwilioProgrammableVideoError::ErrorCode53122 => r#"The recording operation requested is not supported for the Room type"#.into(),
            TwilioProgrammableVideoError::ErrorCode53625 => r#"Access denied to external S3 bucket configured in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53614 => r#"Public key credentials for media tracks encryption could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53611 => r#"Invalid AWS credentials to access external S3 bucket in recording settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53402 => r#"Client is unable to apply a remote media description"#.into(),
            TwilioProgrammableVideoError::ErrorCode53127 => r#"audioOnly no longer supported"#.into(),
            TwilioProgrammableVideoError::ErrorCode53216 => r#"Participant session length exceeded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53101 => r#"Room name is too long"#.into(),
            TwilioProgrammableVideoError::ErrorCode53108 => r#"RoomType is not valid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53613 => r#"AWS credentials to access external S3 bucket could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53400 => r#"Client is unable to create or apply a local media description"#.into(),
            TwilioProgrammableVideoError::ErrorCode53125 => r#"The track kind is not supported by the Room"#.into(),
            TwilioProgrammableVideoError::ErrorCode53111 => r#"StatusCallback is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53607 => r#"Internal failure when updating the recording resource"#.into(),
            TwilioProgrammableVideoError::ErrorCode53003 => r#"Client received an invalid signaling message"#.into(),
            TwilioProgrammableVideoError::ErrorCode53406 => r#"The data channel used by the Data Track had a problem"#.into(),
            TwilioProgrammableVideoError::ErrorCode53667 => r#"AWS credentials to access external S3 bucket could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53004 => r#"Client sent an invalid signaling message"#.into(),
            TwilioProgrammableVideoError::ErrorCode53623 => r#"AWS credentials to access external S3 bucket could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53302 => r#"Track name is too long"#.into(),
            TwilioProgrammableVideoError::ErrorCode53118 => r#"Room Completed Error"#.into(),
            TwilioProgrammableVideoError::ErrorCode53660 => r#"Status Callback response timed out"#.into(),
            TwilioProgrammableVideoError::ErrorCode53666 => r#"Invalid public key for media tracks encryption in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53201 => r#"Participant identity is too long"#.into(),
            TwilioProgrammableVideoError::ErrorCode53124 => r#"The AudioOnly flag is not supported for the Room type"#.into(),
            TwilioProgrammableVideoError::ErrorCode53407 => r#"Media connection failed due to DTLS handshake failure"#.into(),
            TwilioProgrammableVideoError::ErrorCode53631 => r#"Failed to enqueue a room composition from a configured composition hook"#.into(),
            TwilioProgrammableVideoError::ErrorCode53403 => r#"Server is unable to apply a remote media description"#.into(),
            TwilioProgrammableVideoError::ErrorCode53105 => r#"Room contains too many Participants"#.into(),
            TwilioProgrammableVideoError::ErrorCode53303 => r#"Track name contains invalid characters"#.into(),
            TwilioProgrammableVideoError::ErrorCode53610 => r#"Invalid URL for external S3 bucket in recording settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53126 => r#"Legacy room type no longer supported"#.into(),
            TwilioProgrammableVideoError::ErrorCode53602 => r#"AWS encryption key for recording upload is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53119 => r#"The concurrent Rooms quota was exceeded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53604 => r#"Failed to upload the recording to S3"#.into(),
            TwilioProgrammableVideoError::ErrorCode53100 => r#"Room name is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53612 => r#"Invalid public key for media tracks encryption in recording settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53600 => r#"S3 URL for recording upload is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53209 => r#"Participant status is invalid"#.into(),
            TwilioProgrammableVideoError::ErrorCode53624 => r#"Public key credentials for media tracks encryption could not be loaded"#.into(),
            TwilioProgrammableVideoError::ErrorCode53121 => r#"Approaching room or participant concurrency quota"#.into(),
            TwilioProgrammableVideoError::ErrorCode53606 => r#"Internal failure when creating the recording resource"#.into(),
            TwilioProgrammableVideoError::ErrorCode53665 => r#"Invalid AWS credentials to access external S3 bucket in composition settings"#.into(),
            TwilioProgrammableVideoError::ErrorCode53615 => r#"Access denied to external S3 bucket configured in recording settings"#.into()
        }
    }
}
