[package]
name = "twilio-error"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
standard-error = { git = "ssh://git@github.com/AriaBagheri/standard-error-rs", version = "0.1.0" }
