// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioAiAssistantsError;
use standard_error::traits::StandardErrorDescriptionTrait;

impl StandardErrorDescriptionTrait for TwilioAiAssistantsError {
    fn description(&self) -> Option<&'static str> {
        match self {
            TwilioAiAssistantsError::ErrorCode99001 => None,
            TwilioAiAssistantsError::ErrorCode99004 => Some(r#"The response generated by AI Assistants failed the guardrail checks. Our team has been notified and will investigate further."#),
            TwilioAiAssistantsError::ErrorCode99002 => Some(r#"Tool execution responded with non 2xx status code."#),
            TwilioAiAssistantsError::ErrorCode99006 => Some(r#"The provided input schema for AI Assistants Tool is invalid."#),
            TwilioAiAssistantsError::ErrorCode99003 => Some(r#"AI Assistants has flagged the input prompt and therefore will not process the request."#),
            TwilioAiAssistantsError::ErrorCode99005 => Some(r#"AI Assistants cannot access to provided URL."#)
        }
    }
}
