// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioAiAssistantsError;
use standard_error::traits::StandardErrorDocsTrait;

impl StandardErrorDocsTrait for TwilioAiAssistantsError {
    fn docs(&self) -> &'static str {
        match self {
            TwilioAiAssistantsError::ErrorCode99001 => r#"## ERROR - 99001

### General Service Error

 

#### Possible Causes
AI Assistants encountered a general service error.

#### Possible Solutions
No further information available."#,
            TwilioAiAssistantsError::ErrorCode99004 => r#"## ERROR - 99004

### Guardrails response check failed

 The response generated by AI Assistants failed the guardrail checks. Our team has been notified and will investigate further.

#### Possible Causes
No further action is required by you.

#### Possible Solutions
No further action is required by you."#,
            TwilioAiAssistantsError::ErrorCode99002 => r#"## ERROR - 99002

### Tool Execution Error

 Tool execution responded with non 2xx status code.

#### Possible Causes
Tool execution could not be completed due to non 2xx response.

#### Possible Solutions
Check the status code and error logs in your Tool. 
* If you are using Twilio Functions, try adding more `console.logs`, setting Live Logs on the Function, and executing your Assistants again.
* If you are getting 401/403, verify you are handling the X-Twilio-Signature correctly.
* If you are getting 5xx, check your server logs."#,
            TwilioAiAssistantsError::ErrorCode99006 => r#"## ERROR - 99006

### Tool input schema is invalid.

 The provided input schema for AI Assistants Tool is invalid.

#### Possible Causes
You have provided an invalid input schema. Check the Tool setting to verify the schema.

#### Possible Solutions
* Make sure you have `export type Data = ` as your entry point for the input schema
* Verify the provided schema is a valid TypeScript definition"#,
            TwilioAiAssistantsError::ErrorCode99003 => r#"## ERROR - 99003

### Guardrails input check failed

 AI Assistants has flagged the input prompt and therefore will not process the request.

#### Possible Causes
The provided prompt has failed guardrail checks.

#### Possible Solutions
AI Assistants ensure safe, ethical and compliant interactions. Check the provided prompt for any of the following categories:
* Harmful or dangerous content
* Illegal activities
* Medical advice
* Bias, discrimination and hate speech
* Prompt injection
* Sexual and inappropriate content"#,
            TwilioAiAssistantsError::ErrorCode99005 => r#"## ERROR - 99005

### Invalid or Unresolved External Tool Endpoint

 AI Assistants cannot access to provided URL.

#### Possible Causes
Provided URL is invalid or restricted.

#### Possible Solutions
* Verify the provided URL is accessible to the public web."#
        }
    }
}
