// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioMiscellaneousError;
use standard_error::traits::StandardErrorCausesTrait;

impl StandardErrorCausesTrait for TwilioMiscellaneousError {
    fn causes(&self) -> Option<&'static str> {
        match self {
            TwilioMiscellaneousError::ErrorCode13000 => None,
            TwilioMiscellaneousError::ErrorCode21616 => None,
            TwilioMiscellaneousError::ErrorCode13612 => None,
            TwilioMiscellaneousError::ErrorCode19023 => Some(r#"Channel type other than: work, home, other"#),
            TwilioMiscellaneousError::ErrorCode51109 => None,
            TwilioMiscellaneousError::ErrorCode21227 => None,
            TwilioMiscellaneousError::ErrorCode21504 => None,
            TwilioMiscellaneousError::ErrorCode21406 => None,
            TwilioMiscellaneousError::ErrorCode51106 => None,
            TwilioMiscellaneousError::ErrorCode13241 => None,
            TwilioMiscellaneousError::ErrorCode21602 => Some(r#"You may have attempted to send a message without a `Body` or `MediaURL` parameter."#),
            TwilioMiscellaneousError::ErrorCode84004 => Some(r#"- The Create Execution endpoint was called with parameters that could not be processed."#),
            TwilioMiscellaneousError::ErrorCode21477 => None,
            TwilioMiscellaneousError::ErrorCode70156 => None,
            TwilioMiscellaneousError::ErrorCode94601 => Some(r#" * UntilDate is equal or more recent than FromDate."#),
            TwilioMiscellaneousError::ErrorCode19041 => Some(r#"Custom field value is missing, Custom Field value is invalid and/or Custom Field is duplicated"#),
            TwilioMiscellaneousError::ErrorCode21235 => Some(r#"* An IP Access Control List or IP Address with the same FriendlyName may already exist.
* The IP Access Control List may already contain that IP Address"#),
            TwilioMiscellaneousError::ErrorCode21222 => None,
            TwilioMiscellaneousError::ErrorCode91203 => Some(r#"* Deleting a schema is not allowed"#),
            TwilioMiscellaneousError::ErrorCode21237 => Some(r#"* IP Access control lists cannot contain more than 25 Addresses."#),
            TwilioMiscellaneousError::ErrorCode21229 => None,
            TwilioMiscellaneousError::ErrorCode13234 => None,
            TwilioMiscellaneousError::ErrorCode15002 => None,
            TwilioMiscellaneousError::ErrorCode51108 => None,
            TwilioMiscellaneousError::ErrorCode21264 => Some(r#"The ‘From’ number of the inbound call is not a [Verified Caller ID](https://support.twilio.com/hc/en-us/articles/223180048-How-to-Add-and-Remove-a-Verified-Phone-Number-or-Caller-ID-with-Twilio). Trial accounts can only receive inbound calls from verified phone numbers."#),
            TwilioMiscellaneousError::ErrorCode94403 => Some(r#"* Public key specified in Transcription Settings is not found in Twilio Credentials Storage
* Public key defined in credentials resource is invalid and can’t be used to encrypt transcription files
* Public key defined in credentials resource is expired and can’t be used to encrypt transcription files"#),
            TwilioMiscellaneousError::ErrorCode20011 => None,
            TwilioMiscellaneousError::ErrorCode51113 => None,
            TwilioMiscellaneousError::ErrorCode21402 => None,
            TwilioMiscellaneousError::ErrorCode13616 => None,
            TwilioMiscellaneousError::ErrorCode70252 => None,
            TwilioMiscellaneousError::ErrorCode14220 => None,
            TwilioMiscellaneousError::ErrorCode70105 => None,
            TwilioMiscellaneousError::ErrorCode13618 => None,
            TwilioMiscellaneousError::ErrorCode94400 => Some(r#"* Twilio failed to process transcription request and all retries attempts were exhausted
* Twilio failed to normalize and/or store transcription results and all retries attempts were exhausted"#),
            TwilioMiscellaneousError::ErrorCode21475 => None,
            TwilioMiscellaneousError::ErrorCode13310 => None,
            TwilioMiscellaneousError::ErrorCode19035 => Some(r#"Page size specified greater than 25 or less than 1"#),
            TwilioMiscellaneousError::ErrorCode21702 => None,
            TwilioMiscellaneousError::ErrorCode19026 => Some(r#"Attempt to create more than 5 channels of the same type"#),
            TwilioMiscellaneousError::ErrorCode21456 => None,
            TwilioMiscellaneousError::ErrorCode32017 => Some(r#"* The calling number has a low answer rate from end users
* The calling number generates low duration calls
* The calling number is responsible for large volumes of unwanted calls"#),
            TwilioMiscellaneousError::ErrorCode51107 => None,
            TwilioMiscellaneousError::ErrorCode13111 => None,
            TwilioMiscellaneousError::ErrorCode21233 => None,
            TwilioMiscellaneousError::ErrorCode19033 => Some(r#"Invalid length, invalid data type"#),
            TwilioMiscellaneousError::ErrorCode94402 => Some(r#"* Twilio failed to encrypt transcription results and all retries attempts were exhausted"#),
            TwilioMiscellaneousError::ErrorCode80403 => None,
            TwilioMiscellaneousError::ErrorCode19028 => Some(r#"The channel value provided in the request is different from the existing one"#),
            TwilioMiscellaneousError::ErrorCode21623 => None,
            TwilioMiscellaneousError::ErrorCode19012 => Some(r#"User has not provided contact updates"#),
            TwilioMiscellaneousError::ErrorCode60002 => Some(r#"The request was received but failed during processing due to a timeout. If using Silent Network Auth, this can happen when the device does not invoke the SNA URL within the timeout period. The default timeout period is 10 minutes."#),
            TwilioMiscellaneousError::ErrorCode61001 => None,
            TwilioMiscellaneousError::ErrorCode21242 => Some(r#"* Credential Lists cannot contain more than 1000 Credentials."#),
            TwilioMiscellaneousError::ErrorCode32102 => None,
            TwilioMiscellaneousError::ErrorCode90015 => Some(r#"Single create message request has Body and one of Template's field: Template or TemplateSid or TemplateLanguage or TemplateArgs"#),
            TwilioMiscellaneousError::ErrorCode60004 => Some(r#"The request was received but failed due to an invalid configuration."#),
            TwilioMiscellaneousError::ErrorCode51110 => None,
            TwilioMiscellaneousError::ErrorCode22223 => Some(r#"The Regulatory Bundle is either in not in a twilio-approved status or does not have a valid_until date"#),
            TwilioMiscellaneousError::ErrorCode13420 => None,
            TwilioMiscellaneousError::ErrorCode30112 => Some(r#"Wrong account is given"#),
            TwilioMiscellaneousError::ErrorCode51114 => None,
            TwilioMiscellaneousError::ErrorCode21407 => None,
            TwilioMiscellaneousError::ErrorCode21457 => None,
            TwilioMiscellaneousError::ErrorCode51004 => None,
            TwilioMiscellaneousError::ErrorCode94303 => Some(r#"* "Language" value is blank
* "Language" value is null"#),
            TwilioMiscellaneousError::ErrorCode51118 => None,
            TwilioMiscellaneousError::ErrorCode21607 => None,
            TwilioMiscellaneousError::ErrorCode21204 => None,
            TwilioMiscellaneousError::ErrorCode19029 => Some(r#"User has not provided channel updates"#),
            TwilioMiscellaneousError::ErrorCode13230 => None,
            TwilioMiscellaneousError::ErrorCode13222 => None,
            TwilioMiscellaneousError::ErrorCode32112 => Some(r#"* If you specified headers in a SIP URI, invalid characters were most likely introduced by an escaped character. Escaped characters in SIP URIs are defined by a percent sign (%) followed by two hexadecimal digits specifying a character code."#),
            TwilioMiscellaneousError::ErrorCode20004 => None,
            TwilioMiscellaneousError::ErrorCode13617 => None,
            TwilioMiscellaneousError::ErrorCode10003 => Some(r#"*  Lack of funds
*  Violation of the Terms of Service or Acceptable Use Policy"#),
            TwilioMiscellaneousError::ErrorCode19014 => Some(r#"Contact fetch request contains both unique_customer_provided_id and channel"#),
            TwilioMiscellaneousError::ErrorCode21403 => None,
            TwilioMiscellaneousError::ErrorCode21473 => None,
            TwilioMiscellaneousError::ErrorCode90030 => Some(r#"'CorrelationId' field has too long length"#),
            TwilioMiscellaneousError::ErrorCode19022 => Some(r#"Channel other than: email, sms, voice, messenger, whatsapp"#),
            TwilioMiscellaneousError::ErrorCode14213 => None,
            TwilioMiscellaneousError::ErrorCode21478 => None,
            TwilioMiscellaneousError::ErrorCode30016 => None,
            TwilioMiscellaneousError::ErrorCode20422 => None,
            TwilioMiscellaneousError::ErrorCode60005 => Some(r#"The request was received but failed during processing due to an error while communicating with the carrier."#),
            TwilioMiscellaneousError::ErrorCode21218 => None,
            TwilioMiscellaneousError::ErrorCode20021 => Some(r#"* The phone number was rejected by T-Mobile SDG Service Provisioning API"#),
            TwilioMiscellaneousError::ErrorCode90027 => Some(r#"'FriendlyName' field has too long length"#),
            TwilioMiscellaneousError::ErrorCode80606 => None,
            TwilioMiscellaneousError::ErrorCode14204 => None,
            TwilioMiscellaneousError::ErrorCode94304 => Some(r#"* "Language" value is not a BCP-47 code"#),
            TwilioMiscellaneousError::ErrorCode13252 => None,
            TwilioMiscellaneousError::ErrorCode21207 => None,
            TwilioMiscellaneousError::ErrorCode21503 => None,
            TwilioMiscellaneousError::ErrorCode70004 => None,
            TwilioMiscellaneousError::ErrorCode13212 => None,
            TwilioMiscellaneousError::ErrorCode21472 => None,
            TwilioMiscellaneousError::ErrorCode21203 => None,
            TwilioMiscellaneousError::ErrorCode51105 => None,
            TwilioMiscellaneousError::ErrorCode21701 => Some(r#"* The Messaging Service resource you are referencing does not exist.
* The Messaging Service resource you are referencing does not belong to the Account SID in your API Request.
"#),
            TwilioMiscellaneousError::ErrorCode21239 => Some(r#"* An account cannot have more than 100 IP Access Control Lists."#),
            TwilioMiscellaneousError::ErrorCode51201 => None,
            TwilioMiscellaneousError::ErrorCode52116 => Some(r#"Detected the use of a legacy FCM server key credential. This credential will stop working after Google deprecates the legacy FCM API in June 2024. Your action is required in order for FCM push notifications to continue to work after the legacy FCM API is deprecated."#),
            TwilioMiscellaneousError::ErrorCode20423 => None,
            TwilioMiscellaneousError::ErrorCode14221 => None,
            TwilioMiscellaneousError::ErrorCode11243 => None,
            TwilioMiscellaneousError::ErrorCode13611 => None,
            TwilioMiscellaneousError::ErrorCode20012 => Some(r#"Supported Cipher Suites list is not reflecting the reality."#),
            TwilioMiscellaneousError::ErrorCode90016 => Some(r#"Some template parameters are provided but Template (or TemplateSid) itself is not provide."#),
            TwilioMiscellaneousError::ErrorCode21501 => None,
            TwilioMiscellaneousError::ErrorCode19010 => Some(r#"The search parameter provided is not valid"#),
            TwilioMiscellaneousError::ErrorCode32209 => Some(r#"* Media security is enabled on your SIP domain or trunk, but Twilio received SIP traffic over an insecure protocol, such as UDP or TCP.
* You are using SIP registration, and are attempting to place a secure call to an endpoint where all of the available bindings were registered with an insecure protocol, such as UDP or TCP."#),
            TwilioMiscellaneousError::ErrorCode12301 => None,
            TwilioMiscellaneousError::ErrorCode80602 => None,
            TwilioMiscellaneousError::ErrorCode20500 => None,
            TwilioMiscellaneousError::ErrorCode90013 => Some(r#"All next attributes are missing: 'Template', 'TemplateSid', 'TemplateLanguage', 'MediaUrls'"#),
            TwilioMiscellaneousError::ErrorCode21620 => Some(r#"The URL(s) lack a protocol specifier: `http://` or `https://`"#),
            TwilioMiscellaneousError::ErrorCode51003 => None,
            TwilioMiscellaneousError::ErrorCode80903 => None,
            TwilioMiscellaneousError::ErrorCode21608 => None,
            TwilioMiscellaneousError::ErrorCode94500 => Some(r#"* sourceSid value is invalid
* sourceSid is not a call recording sid"#),
            TwilioMiscellaneousError::ErrorCode21220 => None,
            TwilioMiscellaneousError::ErrorCode503 => Some(r#"* The server is currently unable to handle the request.
"#),
            TwilioMiscellaneousError::ErrorCode70052 => None,
            TwilioMiscellaneousError::ErrorCode13233 => None,
            TwilioMiscellaneousError::ErrorCode21613 => None,
            TwilioMiscellaneousError::ErrorCode21502 => None,
            TwilioMiscellaneousError::ErrorCode21231 => None,
            TwilioMiscellaneousError::ErrorCode51130 => None,
            TwilioMiscellaneousError::ErrorCode51116 => None,
            TwilioMiscellaneousError::ErrorCode51006 => None,
            TwilioMiscellaneousError::ErrorCode21101 => None,
            TwilioMiscellaneousError::ErrorCode70104 => None,
            TwilioMiscellaneousError::ErrorCode13313 => None,
            TwilioMiscellaneousError::ErrorCode20007 => None,
            TwilioMiscellaneousError::ErrorCode90017 => Some(r#"'Template' and 'TemplateSid'/'TemplateLanguage' are specified together for template message"#),
            TwilioMiscellaneousError::ErrorCode11202 => None,
            TwilioMiscellaneousError::ErrorCode14101 => None,
            TwilioMiscellaneousError::ErrorCode30012 => None,
            TwilioMiscellaneousError::ErrorCode94200 => Some(r#"* "encryptionEnabled" value is invalid"#),
            TwilioMiscellaneousError::ErrorCode21201 => None,
            TwilioMiscellaneousError::ErrorCode13510 => None,
            TwilioMiscellaneousError::ErrorCode90010 => None,
            TwilioMiscellaneousError::ErrorCode60003 => Some(r#"The request was received and processed successfully but data is not available for the requested end user."#),
            TwilioMiscellaneousError::ErrorCode13614 => None,
            TwilioMiscellaneousError::ErrorCode70155 => None,
            TwilioMiscellaneousError::ErrorCode90037 => Some(r#"To many 'CorrelationId' items in the request"#),
            TwilioMiscellaneousError::ErrorCode21226 => None,
            TwilioMiscellaneousError::ErrorCode21255 => Some(r#"* You cannot have more than 1000 IP Access Control Lists."#),
            TwilioMiscellaneousError::ErrorCode19011 => Some(r#"User provided an invalid JSON or trying to update fields other than first_name, middle_name, last_name, legal_name, preferred_name, unique_customer_provided_id or custom_fields of a contact"#),
            TwilioMiscellaneousError::ErrorCode19031 => Some(r#"Attempt to create more than 5 locations"#),
            TwilioMiscellaneousError::ErrorCode94401 => Some(r#"* The speech-to-text provider failed to transcribe audio"#),
            TwilioMiscellaneousError::ErrorCode70001 => None,
            TwilioMiscellaneousError::ErrorCode90041 => Some(r#"One of 'MediaUrl' fields is too long"#),
            TwilioMiscellaneousError::ErrorCode80906 => None,
            TwilioMiscellaneousError::ErrorCode51125 => None,
            TwilioMiscellaneousError::ErrorCode13226 => None,
            TwilioMiscellaneousError::ErrorCode70251 => None,
            TwilioMiscellaneousError::ErrorCode21409 => None,
            TwilioMiscellaneousError::ErrorCode21422 => None,
            TwilioMiscellaneousError::ErrorCode51126 => None,
            TwilioMiscellaneousError::ErrorCode32006 => None,
            TwilioMiscellaneousError::ErrorCode19027 => Some(r#"Channel description is over 100 chars"#),
            TwilioMiscellaneousError::ErrorCode13615 => None,
            TwilioMiscellaneousError::ErrorCode11242 => None,
            TwilioMiscellaneousError::ErrorCode19021 => Some(r#"Request with is_primary set to True for more than one channel "#),
            TwilioMiscellaneousError::ErrorCode21211 => Some(r#"* The formatting of the `To` number you supplied was invalid.
* You attempted to send a message or place a call from a Twilio number to itself (i.e. putting the same Twilio number in the `To` and `From` parameters).
* You attempted to send a message to Short Code.
* You attempted to send a message to an Alphanumeric Sender ID.
* You attempted to send a message to a `To` number with an invalid prefix using a Messaging Service."#),
            TwilioMiscellaneousError::ErrorCode21705 => Some(r#"* The MessagingServiceSid provided with the request does not match a valid Sid 
   pattern(MGxxx)."#),
            TwilioMiscellaneousError::ErrorCode52004 => Some(r#"Configuration is slightly different depending on which Twilio API and product you are using.

*  Notify: Credential SID can be specified in the Notify Service or in the Binding. This error indicates neither of those were specified.

*  Verify Push: Credential SID can be specified in the Verify Service in the `push` configuration. This error indicates the service doesn't have this configuration.

*  Chat, Voice, Verify, Lookup: Credential SID can be specified in the Twilio Access Token used to register for push notifications. This error indicates that the token missed that information.
"#),
            TwilioMiscellaneousError::ErrorCode13610 => None,
            TwilioMiscellaneousError::ErrorCode21236 => Some(r#"* Your IP Access Control List is still mapped to a SIP Domain."#),
            TwilioMiscellaneousError::ErrorCode21604 => Some(r#"- 'To' phone number is not specified
- Your request is not formatted as `application/x-www-form-urlencoded`"#),
            TwilioMiscellaneousError::ErrorCode19030 => Some(r#"Location type other than: work, home, other"#),
            TwilioMiscellaneousError::ErrorCode94002 => Some(r#"* Transcription Configuration was not specified
* Transcription Configuration was specified but not found in account"#),
            TwilioMiscellaneousError::ErrorCode32216 => Some(r#"The SIP Address exists on a deny list."#),
            TwilioMiscellaneousError::ErrorCode19032 => Some(r#"A Required field is missing or field is invalid or duplicated "#),
            TwilioMiscellaneousError::ErrorCode80105 => None,
            TwilioMiscellaneousError::ErrorCode32016 => Some(r#"PSTN Post-Dial Delay timer (60s) expired due to lack of response from multiple Carriers in route."#),
            TwilioMiscellaneousError::ErrorCode13910 => None,
            TwilioMiscellaneousError::ErrorCode80407 => None,
            TwilioMiscellaneousError::ErrorCode13246 => None,
            TwilioMiscellaneousError::ErrorCode32103 => None,
            TwilioMiscellaneousError::ErrorCode70102 => None,
            TwilioMiscellaneousError::ErrorCode90032 => Some(r#"Broadcast recipient's 'to' has invalid format. For instance, colon is missing."#),
            TwilioMiscellaneousError::ErrorCode11236 => None,
            TwilioMiscellaneousError::ErrorCode14202 => None,
            TwilioMiscellaneousError::ErrorCode11216 => Some(r#"* Your server responded with an non-redirect HTTP status code in the 3xx series. Twilio will only follow redirects for status codes 301, 302, 303, and 307.
* Your server did not include a location header in the redirect response"#),
            TwilioMiscellaneousError::ErrorCode14111 => None,
            TwilioMiscellaneousError::ErrorCode70051 => Some(r#"* The Account is not found or is suspended
* The API key is not found or is suspended
* The Credentials used for authorization do not belong to the given account
* If using a Restricted API Key - the key may be missing a permission to access the resource
* If using a Restricted API Key - permission to access the resource may not be supported"#),
            TwilioMiscellaneousError::ErrorCode21210 => Some(r#"The From number used to make outbound call not a Twilio number or not a verified caller ID"#),
            TwilioMiscellaneousError::ErrorCode80303 => None,
            TwilioMiscellaneousError::ErrorCode80905 => None,
            TwilioMiscellaneousError::ErrorCode61004 => None,
            TwilioMiscellaneousError::ErrorCode13217 => None,
            TwilioMiscellaneousError::ErrorCode80503 => None,
            TwilioMiscellaneousError::ErrorCode11320 => None,
            TwilioMiscellaneousError::ErrorCode13242 => None,
            TwilioMiscellaneousError::ErrorCode13245 => None,
            TwilioMiscellaneousError::ErrorCode51104 => None,
            TwilioMiscellaneousError::ErrorCode51122 => None,
            TwilioMiscellaneousError::ErrorCode20020 => Some(r#"* The data already exist in T-Mobile SDG Service Provisioning API"#),
            TwilioMiscellaneousError::ErrorCode19042 => Some(r#"Invalid length for custom field, data type mismatch and/or date in invalid format"#),
            TwilioMiscellaneousError::ErrorCode12101 => None,
            TwilioMiscellaneousError::ErrorCode14211 => None,
            TwilioMiscellaneousError::ErrorCode21452 => None,
            TwilioMiscellaneousError::ErrorCode61000 => None,
            TwilioMiscellaneousError::ErrorCode21421 => Some(r#"* You tried to purchase or lookup a phone number that is invalid.
* You tried to add an invalid Phone Number SID or Short Code SID to a Messaging Service."#),
            TwilioMiscellaneousError::ErrorCode13312 => None,
            TwilioMiscellaneousError::ErrorCode20429 => Some(r#"Your account is sending too many concurrent Rest API requests to Twilio servers."#),
            TwilioMiscellaneousError::ErrorCode50068 => None,
            TwilioMiscellaneousError::ErrorCode51202 => None,
            TwilioMiscellaneousError::ErrorCode21471 => None,
            TwilioMiscellaneousError::ErrorCode70253 => None,
            TwilioMiscellaneousError::ErrorCode90012 => Some(r#"Too many recipients are provided for a single Broadcast"#),
            TwilioMiscellaneousError::ErrorCode21601 => None,
            TwilioMiscellaneousError::ErrorCode13221 => None,
            TwilioMiscellaneousError::ErrorCode14212 => None,
            TwilioMiscellaneousError::ErrorCode13251 => None,
            TwilioMiscellaneousError::ErrorCode51127 => None,
            TwilioMiscellaneousError::ErrorCode13299 => Some(r#"- "#),
            TwilioMiscellaneousError::ErrorCode403 => Some(r#"Incorrect credentials"#),
            TwilioMiscellaneousError::ErrorCode13231 => None,
            TwilioMiscellaneousError::ErrorCode13120 => None,
            TwilioMiscellaneousError::ErrorCode21653 => Some(r#"Too many recipients were provided in the request or channel selection is incorrect"#),
            TwilioMiscellaneousError::ErrorCode12300 => Some(r#"* Having a phone number, outgoing call request or action attribute refer to a non-XML or audio resource.
* Having a Play verb attempt to play non-audio content, such as XML or text."#),
            TwilioMiscellaneousError::ErrorCode51215 => None,
            TwilioMiscellaneousError::ErrorCode80604 => None,
            TwilioMiscellaneousError::ErrorCode32113 => Some(r#"* SIP header name not supported on the Twilio platform."#),
            TwilioMiscellaneousError::ErrorCode21453 => None,
            TwilioMiscellaneousError::ErrorCode19024 => Some(r#"Required field is missing or field provided is invalid or duplicated"#),
            TwilioMiscellaneousError::ErrorCode11235 => None,
            TwilioMiscellaneousError::ErrorCode90025 => Some(r#"Currently, Twilio supports only data tags ("{{<tag name>}}"). All other Mustache tags/commands are disabled."#),
            TwilioMiscellaneousError::ErrorCode70106 => None,
            TwilioMiscellaneousError::ErrorCode10001 => Some(r#"*  Lack of funds
*   Violation of the Terms of Service or Acceptable Use Policy"#),
            TwilioMiscellaneousError::ErrorCode80605 => None,
            TwilioMiscellaneousError::ErrorCode13112 => None,
            TwilioMiscellaneousError::ErrorCode94100 => Some(r#"* The callback URL specified is incorrect
* Your application has an issue while handling callback requests or suffering and outage"#),
            TwilioMiscellaneousError::ErrorCode90039 => Some(r#"'MessageStatusCallbackUrl' has invalid URL format or schema. Messaging allows only HTTP or HTTPS schemas"#),
            TwilioMiscellaneousError::ErrorCode21209 => None,
            TwilioMiscellaneousError::ErrorCode11203 => None,
            TwilioMiscellaneousError::ErrorCode12100 => None,
            TwilioMiscellaneousError::ErrorCode61008 => None,
            TwilioMiscellaneousError::ErrorCode61005 => None,
            TwilioMiscellaneousError::ErrorCode14106 => None,
            TwilioMiscellaneousError::ErrorCode11217 => Some(r#"* There was an error in your server (500).
* There was a problem between your proxy and your server (502, 503, 504).
* The URL specified in your webhook configuration is incorrect (404, 410).
* Your server is attempting to rate limit Twilio's webhook requests (429). Twilio's webhooks do not support rate limiting.
* Your webhook configuration does not have appropriate permissions to call the configured URL (403)."#),
            TwilioMiscellaneousError::ErrorCode13248 => None,
            TwilioMiscellaneousError::ErrorCode94600 => Some(r#" * There were too many filters applied."#),
            TwilioMiscellaneousError::ErrorCode13244 => None,
            TwilioMiscellaneousError::ErrorCode51131 => None,
            TwilioMiscellaneousError::ErrorCode80902 => None,
            TwilioMiscellaneousError::ErrorCode21420 => None,
            TwilioMiscellaneousError::ErrorCode11237 => None,
            TwilioMiscellaneousError::ErrorCode61003 => None,
            TwilioMiscellaneousError::ErrorCode90022 => Some(r#"One of 'TemplateArgs' dictionary value is too long"#),
            TwilioMiscellaneousError::ErrorCode14108 => None,
            TwilioMiscellaneousError::ErrorCode20002 => None,
            TwilioMiscellaneousError::ErrorCode80406 => None,
            TwilioMiscellaneousError::ErrorCode21618 => None,
            TwilioMiscellaneousError::ErrorCode61007 => None,
            TwilioMiscellaneousError::ErrorCode19034 => Some(r#"Country code is not in the ISO 3166-1 alpha-2 country code of the address format"#),
            TwilioMiscellaneousError::ErrorCode11770 => None,
            TwilioMiscellaneousError::ErrorCode60007 => Some(r#"- Missing App Security Token.
- App Security Token mismatch."#),
            TwilioMiscellaneousError::ErrorCode11300 => None,
            TwilioMiscellaneousError::ErrorCode80307 => Some(r#"Record to be updated is already deleted."#),
            TwilioMiscellaneousError::ErrorCode21241 => Some(r#"* You cannot delete a Credential List that is still mapped to a SIP Domain."#),
            TwilioMiscellaneousError::ErrorCode19050 => Some(r#"We're having trouble completing your request "#),
            TwilioMiscellaneousError::ErrorCode14105 => None,
            TwilioMiscellaneousError::ErrorCode80409 => None,
            TwilioMiscellaneousError::ErrorCode19025 => Some(r#"Invalid length, email or phone in invalid format"#),
            TwilioMiscellaneousError::ErrorCode404 => Some(r#"* The specified resource is no longer available.
"#),
            TwilioMiscellaneousError::ErrorCode13110 => None,
            TwilioMiscellaneousError::ErrorCode11200 => Some(r#"* Web server returned a 4xx or 5xx HTTP response to Twilio
* Network disruptions between Twilio and your web server; these can be within your or Twilio’s infrastructure or wider disruptions to the internet at large.
* Firewalls (network or application level) between Twilio and your infrastructure
* Misconfigured Web Server
* No Content-Type header attached to response
* Content-Type doesn't match actual content, e.g. an MP3 file that is being served with Content-Type: audio/x-wav, instead of Content-Type: audio/mpeg
"#),
            TwilioMiscellaneousError::ErrorCode51111 => None,
            TwilioMiscellaneousError::ErrorCode21224 => None,
            TwilioMiscellaneousError::ErrorCode14203 => None,
            TwilioMiscellaneousError::ErrorCode60006 => Some(r#"The request was received and failed during processing because a downstream provider indicated that the phone number is invalid, although the phone number formatting was valid. This can happen when the end user provides an invalid phone number in error, the phone number is deactivated, suspended, or in the grace period before reassignment, or a fraudulent user purposefully uses an invalid phone number."#),
            TwilioMiscellaneousError::ErrorCode21479 => None,
            TwilioMiscellaneousError::ErrorCode21451 => None,
            TwilioMiscellaneousError::ErrorCode90011 => Some(r#"MessageSid has incorrect sid format or prefix (SM and MM allowed)"#),
            TwilioMiscellaneousError::ErrorCode21480 => None,
            TwilioMiscellaneousError::ErrorCode13322 => None,
            TwilioMiscellaneousError::ErrorCode13254 => None,
            TwilioMiscellaneousError::ErrorCode11251 => None,
            TwilioMiscellaneousError::ErrorCode70103 => None,
            TwilioMiscellaneousError::ErrorCode90034 => Some(r#"'BroadcastStatusCallbackUrl' is too long"#),
            TwilioMiscellaneousError::ErrorCode21212 => Some(r#"* You have supplied a phone number that was not in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
* Your `From` phone number is on a do-not-originate (DNO) list.
* Your [Alphanumeric Sender ID](https://www.twilio.com/docs/glossary/what-alphanumeric-sender-id) is blocked or too generic.
* You are trying to use an Alphanumeric Sender ID on Trial Account. Trial accounts [cannot send from Alphanumeric Sender IDs](https://www.twilio.com/docs/messaging/guides/how-to-use-your-free-trial-account#sending-sms-and-mms-messages).
* Your WhatsApp Sender is not approved.
* You attempted to send a message with a `From` number that has an invalid prefix, using a Messaging Service.
"#),
            TwilioMiscellaneousError::ErrorCode13210 => None,
            TwilioMiscellaneousError::ErrorCode11201 => None,
            TwilioMiscellaneousError::ErrorCode20413 => None,
            TwilioMiscellaneousError::ErrorCode12102 => None,
            TwilioMiscellaneousError::ErrorCode51001 => None,
            TwilioMiscellaneousError::ErrorCode84001 => Some(r#"- Long await on any async await events."#),
            TwilioMiscellaneousError::ErrorCode90029 => Some(r#"Empty string value is used in 'CorrelationId' field"#),
            TwilioMiscellaneousError::ErrorCode19040 => Some(r#"Request with a custom_field that is not defined"#),
            TwilioMiscellaneousError::ErrorCode32111 => Some(r#"* If you specified headers in a SIP URI, invalid characters were most likely introduced by an escaped character. Escaped characters in SIP URIs are defined by a percent sign (%) followed by two hexadecimal digits specifying a character code."#),
            TwilioMiscellaneousError::ErrorCode90018 => Some(r#"'Template' field is too long"#),
            TwilioMiscellaneousError::ErrorCode94001 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode94201 => Some(r#"* "encryptionKeySid" value is invalid
* "encryptionKeySid" not found in Transcription Settings
* "encryptionKeySid" not found in Credentials Storage
* "encryptionKeySid" is not a credential resource of type Public Key"#),
            TwilioMiscellaneousError::ErrorCode13253 => None,
            TwilioMiscellaneousError::ErrorCode19004 => Some(r#"A required field is missing, duplicate field or invalid field name."#),
            TwilioMiscellaneousError::ErrorCode19005 => Some(r#"Invalid string length, invalid data type"#),
            TwilioMiscellaneousError::ErrorCode90019 => Some(r#"Too many items in 'TemplateArgs' dictionary"#),
            TwilioMiscellaneousError::ErrorCode400 => Some(r#"* The resource to be modified has moved into a state that is no longer valid.
* Input on the request did not pass validation."#),
            TwilioMiscellaneousError::ErrorCode13520 => None,
            TwilioMiscellaneousError::ErrorCode21609 => None,
            TwilioMiscellaneousError::ErrorCode51121 => None,
            TwilioMiscellaneousError::ErrorCode84002 => Some(r#"- Possible downstream exceptions."#),
            TwilioMiscellaneousError::ErrorCode11310 => None,
            TwilioMiscellaneousError::ErrorCode60008 => Some(r#"The request was received and failed due to the phone number’s carrier not supporting this endpoint."#),
            TwilioMiscellaneousError::ErrorCode94300 => Some(r#"* Invalid Callback "Url" value
* Invalid Callback "Method" value"#),
            TwilioMiscellaneousError::ErrorCode51112 => None,
            TwilioMiscellaneousError::ErrorCode94301 => Some(r#"* "UniqueName" is blank
* "UniqueName" is null"#),
            TwilioMiscellaneousError::ErrorCode20005 => None,
            TwilioMiscellaneousError::ErrorCode32110 => Some(r#"* The user-portion of the URI contains invalid characters. The user-info portion allows alphanumeric characters, hyphens, underscores, and a small number of additional punctuation characters.
* A URI header or parameter value contains punctuation or whitespace that is not escaped."#),
            TwilioMiscellaneousError::ErrorCode51120 => None,
            TwilioMiscellaneousError::ErrorCode21230 => None,
            TwilioMiscellaneousError::ErrorCode90038 => Some(r#"'BroadcastStatusCallbackUrl' has no Url format or schema is incorrect. Broadcast allows only http and https schemas"#),
            TwilioMiscellaneousError::ErrorCode21214 => None,
            TwilioMiscellaneousError::ErrorCode51007 => Some(r#"Authentication service has rejected provided Access Token.

To check whether the Access Token is structurally correct, you can use the tools available at [jwt.io](https://jwt.io/).

For the details of Twilio's specific Access Token implementation including the grant format, see [the documentation](/docs/api/rest/access-tokens)."#),
            TwilioMiscellaneousError::ErrorCode80603 => Some(r#"A Session exists with the proposed UniqueName."#),
            TwilioMiscellaneousError::ErrorCode90026 => Some(r#"Template body uses incorrect grammar (we support Mustache grammar). For instance empty Mustache placeholder ("{{}}") is not allowed by the grammar."#),
            TwilioMiscellaneousError::ErrorCode13224 => Some(r#"This error occurs when the provided number is not in E.164 format; for example using local dialing pattern 01234567890 instead of the full E.164 address +441234567890. This can also occur when calls are attempted to non-existent country codes, area codes, or exchanges. For example, there is no +693 country code, no +1238 US area code, and no 555 US exchange.

This can also occur with properly-formatted, valid destinations if none of Twilio’s carrier partners are able to deliver the call; for example due to a telecom network outage in the phone number’s local area."#),
            TwilioMiscellaneousError::ErrorCode14206 => None,
            TwilioMiscellaneousError::ErrorCode94604 => Some(r#" * The account has a Legal Hold"#),
            TwilioMiscellaneousError::ErrorCode11241 => Some(r#"* The edge location(s) specified in the 'e' parameter of your connection settings are not currently supported by Twilio."#),
            TwilioMiscellaneousError::ErrorCode13237 => None,
            TwilioMiscellaneousError::ErrorCode80405 => None,
            TwilioMiscellaneousError::ErrorCode21474 => None,
            TwilioMiscellaneousError::ErrorCode13250 => None,
            TwilioMiscellaneousError::ErrorCode13314 => None,
            TwilioMiscellaneousError::ErrorCode50069 => None,
            TwilioMiscellaneousError::ErrorCode51119 => None,
            TwilioMiscellaneousError::ErrorCode80610 => None,
            TwilioMiscellaneousError::ErrorCode21213 => None,
            TwilioMiscellaneousError::ErrorCode90036 => Some(r#"Recipient's 'body' is too long"#),
            TwilioMiscellaneousError::ErrorCode13211 => None,
            TwilioMiscellaneousError::ErrorCode51005 => None,
            TwilioMiscellaneousError::ErrorCode12400 => None,
            TwilioMiscellaneousError::ErrorCode32114 => Some(r#"* If using the "secure" parameter, allowed values are "true" and "false". Any other value will be treated as "false" and trigger this warning."#),
            TwilioMiscellaneousError::ErrorCode21450 => None,
            TwilioMiscellaneousError::ErrorCode21454 => None,
            TwilioMiscellaneousError::ErrorCode21626 => None,
            TwilioMiscellaneousError::ErrorCode13410 => None,
            TwilioMiscellaneousError::ErrorCode21401 => Some(r#"The phone number is not supported in North America."#),
            TwilioMiscellaneousError::ErrorCode70153 => None,
            TwilioMiscellaneousError::ErrorCode70152 => None,
            TwilioMiscellaneousError::ErrorCode80202 => None,
            TwilioMiscellaneousError::ErrorCode20503 => None,
            TwilioMiscellaneousError::ErrorCode94000 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode13232 => None,
            TwilioMiscellaneousError::ErrorCode21901 => Some(r#"Too long DltTemplateId or its format is invalid"#),
            TwilioMiscellaneousError::ErrorCode19013 => Some(r#"Contact does not possess even one required field"#),
            TwilioMiscellaneousError::ErrorCode10004 => Some(r#"Trial accounts and newly upgraded accounts without an approved Primary Customer Profile have limited concurrent calls."#),
            TwilioMiscellaneousError::ErrorCode19037 => Some(r#"User has not provided location updates"#),
            TwilioMiscellaneousError::ErrorCode13213 => None,
            TwilioMiscellaneousError::ErrorCode11205 => Some(r#"*  Network outages between Twilio and your web server.
*  URLs that reference private IP addresses or localhost.
*  Twilio’s TCP timeout is 10 seconds. If you see an error in Request Inspector after more than 10000 milliseconds, Twilio could locate your server, but could not establish a TCP connection with it. 
*  Twilio’s HTTP timeout is 15 seconds. If you see an error in Request Inspector returned after more than 15000 milliseconds, Twilio was able to establish a TCP connection with your server, but the HTTP response from the server failed."#),
            TwilioMiscellaneousError::ErrorCode51102 => None,
            TwilioMiscellaneousError::ErrorCode51129 => None,
            TwilioMiscellaneousError::ErrorCode14223 => None,
            TwilioMiscellaneousError::ErrorCode410 => Some(r#"* The resource has reached a terminal state and is no longer available.
"#),
            TwilioMiscellaneousError::ErrorCode94602 => Some(r#"* FromDate is a future date."#),
            TwilioMiscellaneousError::ErrorCode20003 => Some(r#"* Using the wrong combination of Account SID and Auth Token 
* Using Test Credentials to access your Live Account
* Using subaccount credentials to access master account
* Previous Auth Token has been deleted
* Attempted API Key has been deleted
* Account is suspended or closed
* Extra characters or spaces in the supplied credentials
* Web proxy is stripping out credentials before forwarding to Twilio
* Using JWT with Auth Token rather than API Key
* Attempted API Key is for the incorrect Twilio Region"#),
            TwilioMiscellaneousError::ErrorCode80701 => None,
            TwilioMiscellaneousError::ErrorCode21217 => None,
            TwilioMiscellaneousError::ErrorCode21621 => Some(r#"The `From` phone number is not capable of sending MMS."#),
            TwilioMiscellaneousError::ErrorCode13249 => None,
            TwilioMiscellaneousError::ErrorCode13215 => None,
            TwilioMiscellaneousError::ErrorCode21202 => None,
            TwilioMiscellaneousError::ErrorCode21225 => None,
            TwilioMiscellaneousError::ErrorCode21455 => None,
            TwilioMiscellaneousError::ErrorCode94101 => Some(r#"* The server receiving status callbacks sent by Twilio takes too long to respond"#),
            TwilioMiscellaneousError::ErrorCode13235 => None,
            TwilioMiscellaneousError::ErrorCode51128 => None,
            TwilioMiscellaneousError::ErrorCode13236 => None,
            TwilioMiscellaneousError::ErrorCode21405 => None,
            TwilioMiscellaneousError::ErrorCode70002 => None,
            TwilioMiscellaneousError::ErrorCode21223 => None,
            TwilioMiscellaneousError::ErrorCode21900 => Some(r#"The format or size of DltPEId is invalid"#),
            TwilioMiscellaneousError::ErrorCode15003 => Some(r#"*  Your application returned a 4xx or 5xx HTTP response to Twilio."#),
            TwilioMiscellaneousError::ErrorCode19003 => Some(r#"An existing contact has the same unique_customer_provided_id value provided in the request"#),
            TwilioMiscellaneousError::ErrorCode15000 => None,
            TwilioMiscellaneousError::ErrorCode21240 => Some(r#"* A Credential List with the same FriendlyName may already exist
* A Username was not provided. A Username must be provided and it must have 32 characters or less
* The password was not provided. A password is required that meets the following criteria:
    * Minimum 12 characters
    * At least one mixed case
    * At least one digit"#),
            TwilioMiscellaneousError::ErrorCode21206 => None,
            TwilioMiscellaneousError::ErrorCode70053 => None,
            TwilioMiscellaneousError::ErrorCode80205 => None,
            TwilioMiscellaneousError::ErrorCode21228 => None,
            TwilioMiscellaneousError::ErrorCode21232 => None,
            TwilioMiscellaneousError::ErrorCode91202 => Some(r#"* Schema not found
* Event Type Not found"#),
            TwilioMiscellaneousError::ErrorCode51103 => None,
            TwilioMiscellaneousError::ErrorCode80908 => None,
            TwilioMiscellaneousError::ErrorCode80601 => None,
            TwilioMiscellaneousError::ErrorCode13710 => None,
            TwilioMiscellaneousError::ErrorCode14104 => None,
            TwilioMiscellaneousError::ErrorCode80402 => None,
            TwilioMiscellaneousError::ErrorCode90020 => Some(r#"One of 'TemplateArgs' dictionary key is blank"#),
            TwilioMiscellaneousError::ErrorCode21221 => None,
            TwilioMiscellaneousError::ErrorCode20001 => None,
            TwilioMiscellaneousError::ErrorCode90028 => Some(r#"'IdempotencyToken' field value has too long length"#),
            TwilioMiscellaneousError::ErrorCode30014 => None,
            TwilioMiscellaneousError::ErrorCode21100 => None,
            TwilioMiscellaneousError::ErrorCode21476 => None,
            TwilioMiscellaneousError::ErrorCode20426 => None,
            TwilioMiscellaneousError::ErrorCode90033 => Some(r#"Too long address and channel are used in Recipient's 'to'"#),
            TwilioMiscellaneousError::ErrorCode20009 => Some(r#"* You requested the call or message be deleted before all of Twilio's systems finished processing it.
* In rare cases, a message or call record may take up to 14 days to be finalized and able to be deleted."#),
            TwilioMiscellaneousError::ErrorCode94302 => Some(r#"* "UniqueName" already associated to another configuration
* "UniqueName" is blank or null
* Invalid "UniqueName" value: Length should be between 1 and 50 characters, can’t contain blank spaces or special characters and can’t be a Transcription Configuration Sid"#),
            TwilioMiscellaneousError::ErrorCode13613 => None,
            TwilioMiscellaneousError::ErrorCode11210 => Some(r#"* URL references a locally defined hostname (check your `/etc/hosts`)
* URL references an undefined hostname"#),
            TwilioMiscellaneousError::ErrorCode21219 => None,
            TwilioMiscellaneousError::ErrorCode21404 => None,
            TwilioMiscellaneousError::ErrorCode21622 => None,
            TwilioMiscellaneousError::ErrorCode61002 => None,
            TwilioMiscellaneousError::ErrorCode20008 => None,
            TwilioMiscellaneousError::ErrorCode51115 => None,
            TwilioMiscellaneousError::ErrorCode61006 => None,
            TwilioMiscellaneousError::ErrorCode20010 => None,
            TwilioMiscellaneousError::ErrorCode84003 => Some(r#"- Liquid values used in the block might not be correct."#),
            TwilioMiscellaneousError::ErrorCode21208 => None,
            TwilioMiscellaneousError::ErrorCode21200 => None,
            TwilioMiscellaneousError::ErrorCode90023 => Some(r#"One of 'TemplateArgs' dictionary value is null"#),
            TwilioMiscellaneousError::ErrorCode90035 => Some(r#"'MessageStatusCallbackUrl' is too long"#),
            TwilioMiscellaneousError::ErrorCode80609 => None,
            TwilioMiscellaneousError::ErrorCode51124 => None,
            TwilioMiscellaneousError::ErrorCode70005 => None,
            TwilioMiscellaneousError::ErrorCode14205 => None,
            TwilioMiscellaneousError::ErrorCode80408 => None,
            TwilioMiscellaneousError::ErrorCode13243 => None,
            TwilioMiscellaneousError::ErrorCode21238 => Some(r#"* One of the parameters passed when creating or updating an Address was incorrect."#),
            TwilioMiscellaneousError::ErrorCode13320 => None,
            TwilioMiscellaneousError::ErrorCode30015 => None,
            TwilioMiscellaneousError::ErrorCode50353 => Some(r#"Request contains already existing Conversation unique name."#),
            TwilioMiscellaneousError::ErrorCode21458 => None,
            TwilioMiscellaneousError::ErrorCode14201 => None,
            TwilioMiscellaneousError::ErrorCode70101 => None,
            TwilioMiscellaneousError::ErrorCode21243 => Some(r#"* One of the parameters passed when creating or updating a Credential was incorrect."#),
            TwilioMiscellaneousError::ErrorCode51123 => None,
            TwilioMiscellaneousError::ErrorCode20023 => Some(r#"* The phone number entered is not correct: either it is null or it has non-decimal symbols."#),
            TwilioMiscellaneousError::ErrorCode70151 => None,
            TwilioMiscellaneousError::ErrorCode51002 => None,
            TwilioMiscellaneousError::ErrorCode80102 => None,
            TwilioMiscellaneousError::ErrorCode70003 => None,
            TwilioMiscellaneousError::ErrorCode90024 => Some(r#"Template body has wider tag's set than specified in 'TemplateArgs' dictionary"#),
            TwilioMiscellaneousError::ErrorCode13255 => None,
            TwilioMiscellaneousError::ErrorCode14215 => None,
            TwilioMiscellaneousError::ErrorCode14102 => None,
            TwilioMiscellaneousError::ErrorCode12200 => Some(r#"* Misspelled verbs
* Incorrect case for verbs; TwiML is case-sensitive, so &lt;Say&gt; works, but &lt;say&gt; will not
* Misspelled or unknown attributes
* Unknown or unexpected nested elements."#),
            TwilioMiscellaneousError::ErrorCode94501 => Some(r#" * Status value is invalid."#),
            TwilioMiscellaneousError::ErrorCode80907 => None,
            TwilioMiscellaneousError::ErrorCode61009 => None,
            TwilioMiscellaneousError::ErrorCode20006 => None,
            TwilioMiscellaneousError::ErrorCode14110 => None,
            TwilioMiscellaneousError::ErrorCode80104 => None,
            TwilioMiscellaneousError::ErrorCode11215 => None,
            TwilioMiscellaneousError::ErrorCode14210 => None,
            TwilioMiscellaneousError::ErrorCode21205 => None,
            TwilioMiscellaneousError::ErrorCode19036 => Some(r#"Page token provided is not an integer"#),
            TwilioMiscellaneousError::ErrorCode60001 => Some(r#"The request was received and passed Twilio API authentication, but failed due to a downstream authentication error for the Account SID provided."#),
            TwilioMiscellaneousError::ErrorCode70154 => None,
            TwilioMiscellaneousError::ErrorCode14103 => None,
            TwilioMiscellaneousError::ErrorCode13201 => None,
            TwilioMiscellaneousError::ErrorCode13311 => None,
            TwilioMiscellaneousError::ErrorCode11240 => Some(r#"* The edge location(s) specified in the 'e' parameter of your connection settings are not valid"#),
            TwilioMiscellaneousError::ErrorCode11220 => Some(r#"*  Incompatible cipher suites in use by the client and the server. This would require the client to use (or enable) a cipher suite that is supported by the server."#),
            TwilioMiscellaneousError::ErrorCode21470 => None,
            TwilioMiscellaneousError::ErrorCode19020 => Some(r#"An existing contact has the same channel value provided in the request "#),
            TwilioMiscellaneousError::ErrorCode30013 => None,
            TwilioMiscellaneousError::ErrorCode51101 => None,
            TwilioMiscellaneousError::ErrorCode94603 => Some(r#" * Ttl is smaller than 1 seconds
 * Ttl is bigger  than 3600 seconds"#),
            TwilioMiscellaneousError::ErrorCode51117 => None,
            TwilioMiscellaneousError::ErrorCode21617 => Some(r#"The maximum allowable body text length is generally 1600 characters, but some special characters such as emojis, emoticons or non-GSM characters will be counted as multiple characters if they have a higher byte count. "#),
            TwilioMiscellaneousError::ErrorCode90040 => Some(r#"Broadcast request has too many 'MediaUrl' fields "#),
            TwilioMiscellaneousError::ErrorCode90021 => Some(r#"One of 'TemplateArgs' dictionary key is too long"#),
            TwilioMiscellaneousError::ErrorCode84000 => Some(r#"There are too many steps in the flow"#),
            TwilioMiscellaneousError::ErrorCode80401 => None,
            TwilioMiscellaneousError::ErrorCode13325 => None
        }
    }
}
