// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioMiscellaneousError;
use standard_error::traits::StandardErrorSolutionsTrait;

impl StandardErrorSolutionsTrait for TwilioMiscellaneousError {
    fn solutions(&self) -> Option<&'static str> {
        match self {
            TwilioMiscellaneousError::ErrorCode13000 => None,
            TwilioMiscellaneousError::ErrorCode21616 => None,
            TwilioMiscellaneousError::ErrorCode13612 => None,
            TwilioMiscellaneousError::ErrorCode19023 => Some(r#"Only work, home or other are valid channels types"#),
            TwilioMiscellaneousError::ErrorCode51109 => None,
            TwilioMiscellaneousError::ErrorCode21227 => None,
            TwilioMiscellaneousError::ErrorCode21504 => None,
            TwilioMiscellaneousError::ErrorCode21406 => None,
            TwilioMiscellaneousError::ErrorCode51106 => None,
            TwilioMiscellaneousError::ErrorCode13241 => None,
            TwilioMiscellaneousError::ErrorCode21602 => Some(r#" Retry your message including a body or a link to some media. For sample code that shows how to send an SMS message with Twilio's supported helper libraries, cURL, or the Twilio CLI, please see [this short tutorial](https://www.twilio.com/docs/sms/send-messages)"#),
            TwilioMiscellaneousError::ErrorCode84004 => Some(r#"- Double-check the provided parameters for syntax errors."#),
            TwilioMiscellaneousError::ErrorCode21477 => None,
            TwilioMiscellaneousError::ErrorCode70156 => None,
            TwilioMiscellaneousError::ErrorCode94601 => Some(r#" * FromDate should be a recent date than UntilDate."#),
            TwilioMiscellaneousError::ErrorCode19041 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode21235 => Some(r#"* Use a different FriendlyName
* Make sure the IP Access Control List does not already contain that IP Address."#),
            TwilioMiscellaneousError::ErrorCode21222 => None,
            TwilioMiscellaneousError::ErrorCode91203 => Some(r#"* Avoid executing a DELETE action against the Schema resource"#),
            TwilioMiscellaneousError::ErrorCode21237 => Some(r#"* Remove IP Addresses from your IP Access Control List if you must create new ones."#),
            TwilioMiscellaneousError::ErrorCode21229 => None,
            TwilioMiscellaneousError::ErrorCode13234 => None,
            TwilioMiscellaneousError::ErrorCode15002 => None,
            TwilioMiscellaneousError::ErrorCode51108 => None,
            TwilioMiscellaneousError::ErrorCode21264 => Some(r#"You can verify phone numbers from the [phone numbers section](https://www.twilio.com/user/account/phone-numbers) of your account portal."#),
            TwilioMiscellaneousError::ErrorCode94403 => Some(r#"* Ensure public key is correct in credentials resource
* Set a different public key that can be used to encrypt transcription results or disable encryption"#),
            TwilioMiscellaneousError::ErrorCode20011 => None,
            TwilioMiscellaneousError::ErrorCode51113 => None,
            TwilioMiscellaneousError::ErrorCode21402 => None,
            TwilioMiscellaneousError::ErrorCode13616 => None,
            TwilioMiscellaneousError::ErrorCode70252 => None,
            TwilioMiscellaneousError::ErrorCode14220 => None,
            TwilioMiscellaneousError::ErrorCode70105 => None,
            TwilioMiscellaneousError::ErrorCode13618 => None,
            TwilioMiscellaneousError::ErrorCode94400 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode21475 => None,
            TwilioMiscellaneousError::ErrorCode13310 => None,
            TwilioMiscellaneousError::ErrorCode19035 => Some(r#"Page size must be between 1 and 25"#),
            TwilioMiscellaneousError::ErrorCode21702 => None,
            TwilioMiscellaneousError::ErrorCode19026 => Some(r#"Only 5 channels of the same type are allowed"#),
            TwilioMiscellaneousError::ErrorCode21456 => None,
            TwilioMiscellaneousError::ErrorCode32017 => Some(r#"Register the telephone numbers with the analytic providers. To reach the major mobile carrier's analytic providers, please register the telephone numbers at www.freecallerregistry.com . To reach T-Mobile's analytic provider directly to register numbers, please go to https://portal.firstorion.com to register numbers. Going direct to the analytic provider has a faster turnaround of being registered / call being delivered to end user"#),
            TwilioMiscellaneousError::ErrorCode51107 => None,
            TwilioMiscellaneousError::ErrorCode13111 => None,
            TwilioMiscellaneousError::ErrorCode21233 => None,
            TwilioMiscellaneousError::ErrorCode19033 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode94402 => Some(r#"* Set a public key that can be used to encrypt transcription results or disable encryption so future transcriptions can be successfully processed and stored"#),
            TwilioMiscellaneousError::ErrorCode80403 => None,
            TwilioMiscellaneousError::ErrorCode19028 => Some(r#"Remove channel value from the request or Delete the existing channel and create a then new one with the new value"#),
            TwilioMiscellaneousError::ErrorCode21623 => None,
            TwilioMiscellaneousError::ErrorCode19012 => Some(r#"When updating a contact at least one field should be updated"#),
            TwilioMiscellaneousError::ErrorCode60002 => Some(r#"Resend request for this phone number to restart timeout period."#),
            TwilioMiscellaneousError::ErrorCode61001 => None,
            TwilioMiscellaneousError::ErrorCode21242 => Some(r#"* Delete Credentials from your Credential List if you must create more."#),
            TwilioMiscellaneousError::ErrorCode32102 => None,
            TwilioMiscellaneousError::ErrorCode90015 => Some(r#"Choose which type of message would you like to use: templated message or plain message."#),
            TwilioMiscellaneousError::ErrorCode60004 => Some(r#"- Check that the Account SID provided is correct.
- [Contact Twilio Support](https://www.twilio.com/help/contact) to confirm that access to this endpoint is enabled for the given Account SID."#),
            TwilioMiscellaneousError::ErrorCode51110 => None,
            TwilioMiscellaneousError::ErrorCode22223 => Some(r#"Select a Regulatory Bundle that is eligible to be Copied by filtering the Regulatory Bundle list with a valid_until date and in the twilio-approved status."#),
            TwilioMiscellaneousError::ErrorCode13420 => None,
            TwilioMiscellaneousError::ErrorCode30112 => Some(r#"Specify the correct account"#),
            TwilioMiscellaneousError::ErrorCode51114 => None,
            TwilioMiscellaneousError::ErrorCode21407 => None,
            TwilioMiscellaneousError::ErrorCode21457 => None,
            TwilioMiscellaneousError::ErrorCode51004 => None,
            TwilioMiscellaneousError::ErrorCode94303 => Some(r#"* Specify a valid "language" as a BCP-47 code"#),
            TwilioMiscellaneousError::ErrorCode51118 => None,
            TwilioMiscellaneousError::ErrorCode21607 => None,
            TwilioMiscellaneousError::ErrorCode21204 => None,
            TwilioMiscellaneousError::ErrorCode19029 => Some(r#"When updating a channel at least one field should be updated"#),
            TwilioMiscellaneousError::ErrorCode13230 => None,
            TwilioMiscellaneousError::ErrorCode13222 => None,
            TwilioMiscellaneousError::ErrorCode32112 => Some(r#"* If you are generating SIP headers from user input, ensure your application properly accounts for non-alphanumeric characters such as punctuation and whitespace, as well as international characters."#),
            TwilioMiscellaneousError::ErrorCode20004 => None,
            TwilioMiscellaneousError::ErrorCode13617 => None,
            TwilioMiscellaneousError::ErrorCode10003 => Some(r#"*  Check your account balance.  Refill funds if necessary.	
*  Contact Twilio <a href="/help/contact">customer support</a> to inquire further."#),
            TwilioMiscellaneousError::ErrorCode19014 => Some(r#"Contact can be fetched either by unique_customer_provided_id or by channel"#),
            TwilioMiscellaneousError::ErrorCode21403 => None,
            TwilioMiscellaneousError::ErrorCode21473 => None,
            TwilioMiscellaneousError::ErrorCode90030 => Some(r#"Use shorter 'CorrelationId' valuer"#),
            TwilioMiscellaneousError::ErrorCode19022 => Some(r#"Only email, sms, voice, messenger or whatsapp are valid channels"#),
            TwilioMiscellaneousError::ErrorCode14213 => None,
            TwilioMiscellaneousError::ErrorCode21478 => None,
            TwilioMiscellaneousError::ErrorCode30016 => None,
            TwilioMiscellaneousError::ErrorCode20422 => None,
            TwilioMiscellaneousError::ErrorCode60005 => Some(r#"- Retry request to rule out transient carrier connection issues. 
- If error persists, [contact Twilio Support](https://www.twilio.com/help/contact) to rule out integration issues."#),
            TwilioMiscellaneousError::ErrorCode21218 => None,
            TwilioMiscellaneousError::ErrorCode20021 => Some(r#"* Check the phone number"#),
            TwilioMiscellaneousError::ErrorCode90027 => Some(r#"Use shorter string as Broadcast 'FriendlyName'"#),
            TwilioMiscellaneousError::ErrorCode80606 => None,
            TwilioMiscellaneousError::ErrorCode14204 => None,
            TwilioMiscellaneousError::ErrorCode94304 => Some(r#"* Specify a valid "language" as a BCP-47 code"#),
            TwilioMiscellaneousError::ErrorCode13252 => None,
            TwilioMiscellaneousError::ErrorCode21207 => None,
            TwilioMiscellaneousError::ErrorCode21503 => None,
            TwilioMiscellaneousError::ErrorCode70004 => None,
            TwilioMiscellaneousError::ErrorCode13212 => None,
            TwilioMiscellaneousError::ErrorCode21472 => None,
            TwilioMiscellaneousError::ErrorCode21203 => None,
            TwilioMiscellaneousError::ErrorCode51105 => None,
            TwilioMiscellaneousError::ErrorCode21701 => Some(r#"*  Double check the `Messaging Service SID` and `Account SID` parameters that you are using. You can find the Messaging Service SID in the [Twilio Console](https://console.twilio.com/us1/develop/sms/services) (beginning with MG)."#),
            TwilioMiscellaneousError::ErrorCode21239 => Some(r#"* Delete an existing IP Access Control List if you must create more."#),
            TwilioMiscellaneousError::ErrorCode51201 => None,
            TwilioMiscellaneousError::ErrorCode52116 => Some(r#"Use a new FCMv1 credential before June 2024 to keep sending push notifications. See instructions linked in the description above."#),
            TwilioMiscellaneousError::ErrorCode20423 => None,
            TwilioMiscellaneousError::ErrorCode14221 => None,
            TwilioMiscellaneousError::ErrorCode11243 => None,
            TwilioMiscellaneousError::ErrorCode13611 => None,
            TwilioMiscellaneousError::ErrorCode20012 => Some(r#"Changed with the real list which is checked "#),
            TwilioMiscellaneousError::ErrorCode90016 => Some(r#"Provide Template or TemplateSid&TemplateLanguage in the create message request"#),
            TwilioMiscellaneousError::ErrorCode21501 => None,
            TwilioMiscellaneousError::ErrorCode19010 => Some(r#"Review the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode32209 => Some(r#"* Please ensure your PBX or end device is configured to send SIP traffic over the TLS transport.
* If you are using SIP registration, your device must be configured to *register* over the TLS protocol. Devices registered over insecure protocols will not be attempted for secure calls."#),
            TwilioMiscellaneousError::ErrorCode12301 => None,
            TwilioMiscellaneousError::ErrorCode80602 => None,
            TwilioMiscellaneousError::ErrorCode20500 => None,
            TwilioMiscellaneousError::ErrorCode90013 => Some(r#"Use one of the attributes 'Template', 'TemplateSid', 'TemplateLanguage', 'MediaUrls' to specify Broadcast content"#),
            TwilioMiscellaneousError::ErrorCode21620 => Some(r#"Add a correct protocol specifier prefix: `http://` or `https://`"#),
            TwilioMiscellaneousError::ErrorCode51003 => None,
            TwilioMiscellaneousError::ErrorCode80903 => None,
            TwilioMiscellaneousError::ErrorCode21608 => None,
            TwilioMiscellaneousError::ErrorCode94500 => Some(r#" * Specify a sourceSid of a valid call recording"#),
            TwilioMiscellaneousError::ErrorCode21220 => None,
            TwilioMiscellaneousError::ErrorCode503 => Some(r#"* Retry the request at a later time."#),
            TwilioMiscellaneousError::ErrorCode70052 => None,
            TwilioMiscellaneousError::ErrorCode13233 => None,
            TwilioMiscellaneousError::ErrorCode21613 => None,
            TwilioMiscellaneousError::ErrorCode21502 => None,
            TwilioMiscellaneousError::ErrorCode21231 => None,
            TwilioMiscellaneousError::ErrorCode51130 => None,
            TwilioMiscellaneousError::ErrorCode51116 => None,
            TwilioMiscellaneousError::ErrorCode51006 => None,
            TwilioMiscellaneousError::ErrorCode21101 => None,
            TwilioMiscellaneousError::ErrorCode70104 => None,
            TwilioMiscellaneousError::ErrorCode13313 => None,
            TwilioMiscellaneousError::ErrorCode20007 => None,
            TwilioMiscellaneousError::ErrorCode90017 => Some(r#"Choose which template message to use Direcy('Template') or Indirect('TemplateSid')"#),
            TwilioMiscellaneousError::ErrorCode11202 => None,
            TwilioMiscellaneousError::ErrorCode14101 => None,
            TwilioMiscellaneousError::ErrorCode30012 => None,
            TwilioMiscellaneousError::ErrorCode94200 => Some(r#"* Set "encryptionEnabled" value to true to enable encryption for transcriptions
* Set "encryptionEnabled" value to false to disable encryption for transcriptions"#),
            TwilioMiscellaneousError::ErrorCode21201 => None,
            TwilioMiscellaneousError::ErrorCode13510 => None,
            TwilioMiscellaneousError::ErrorCode90010 => None,
            TwilioMiscellaneousError::ErrorCode60003 => Some(r#"Do not retry request for this end user."#),
            TwilioMiscellaneousError::ErrorCode13614 => None,
            TwilioMiscellaneousError::ErrorCode70155 => None,
            TwilioMiscellaneousError::ErrorCode90037 => Some(r#"Use no more than allowed number of 'CorrelationId' fields"#),
            TwilioMiscellaneousError::ErrorCode21226 => None,
            TwilioMiscellaneousError::ErrorCode21255 => Some(r#"* Remove current IP Access Control Lists if you must create new ones."#),
            TwilioMiscellaneousError::ErrorCode19011 => Some(r#"Fix JSON input or change update contact request to update only first_name, middle_name, last_name, legal_name, preferred_name, unique_customer_provided_id or custom_fields"#),
            TwilioMiscellaneousError::ErrorCode19031 => Some(r#"Remove an existing location to add a new one"#),
            TwilioMiscellaneousError::ErrorCode94401 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode70001 => None,
            TwilioMiscellaneousError::ErrorCode90041 => Some(r#"Use shorter 'MediaUrl' value"#),
            TwilioMiscellaneousError::ErrorCode80906 => None,
            TwilioMiscellaneousError::ErrorCode51125 => None,
            TwilioMiscellaneousError::ErrorCode13226 => None,
            TwilioMiscellaneousError::ErrorCode70251 => None,
            TwilioMiscellaneousError::ErrorCode21409 => None,
            TwilioMiscellaneousError::ErrorCode21422 => None,
            TwilioMiscellaneousError::ErrorCode51126 => None,
            TwilioMiscellaneousError::ErrorCode32006 => None,
            TwilioMiscellaneousError::ErrorCode19027 => Some(r#"Channel description must be under 100 chars"#),
            TwilioMiscellaneousError::ErrorCode13615 => None,
            TwilioMiscellaneousError::ErrorCode11242 => None,
            TwilioMiscellaneousError::ErrorCode19021 => Some(r#"Ensure only each channel has only 1 is_primary set to true"#),
            TwilioMiscellaneousError::ErrorCode21211 => Some(r#"* Ensure you have formatted your phone numbers in [E164
format](http://en.wikipedia.org/wiki/E.164): `[+] [country code] [subscriber number including area code]`.
* Ensure you have used the correct [country calling code](https://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_listing_by_country_or_region) for the phone number you are calling.
* Ensure you are not attempting to call or message from a Twilio number to itself.
* Ensure you are not attempting to send messages to Short Codes or Alphanumeric Sender IDs. These sender types cannot receive messages from Twilio numbers.
* Review the 'To' number for any typos or incorrect input methods.
* If you are using a third party integration, test your API request in the [Try it out](https://console.twilio.com/us1/develop/sms/try-it-out/send-an-sms) section of the Twilio console. If this is successful, you may need to contact the third party to ensure they are not making unexpected changes to your `To` parameter.
* When sending messages using a Messaging Service, instead of formatting a `To` number with an invalid prefix, remove the prefix and send directly to the `To` number using [E164
format](http://en.wikipedia.org/wiki/E.164): `[+] [country code] [subscriber number including area code]`. If the `To` number is able to accept RCS messages and there is an RCS Agent available in the Messaging Service Sender Pool, it will be selected to send to the given `To` number.
"#),
            TwilioMiscellaneousError::ErrorCode21705 => Some(r#"* Double check the Messaging Service Sid parameter that you are using.
* Find a specific Messaging Service Sid and manage your Messaging Services in the 
  [Twilio Console](https://www.twilio.com/console/sms/services)."#),
            TwilioMiscellaneousError::ErrorCode52004 => Some(r#"*  Notify: Set the Credential SID either in the Notify Service or in the Create Binding request
*  Verify Push: Set the FCM/APN Credential SID in the Verify Service
*  Chat, Voice, Verify, Lookup: Set the Credential SID in the Access Token"#),
            TwilioMiscellaneousError::ErrorCode13610 => None,
            TwilioMiscellaneousError::ErrorCode21236 => Some(r#"* Remove the IP Access Control list from your SIP Domain before trying to delete it."#),
            TwilioMiscellaneousError::ErrorCode21604 => Some(r#"- Make sure to include a 'To' phone number
- Check that you are submitting your request as `application/x-www-form-urlencoded` and not as `json`."#),
            TwilioMiscellaneousError::ErrorCode19030 => Some(r#"Only use work, home, other as location type"#),
            TwilioMiscellaneousError::ErrorCode94002 => Some(r#"* Specify unique name or Sid of an existent Transcription Configuration associated to your account"#),
            TwilioMiscellaneousError::ErrorCode32216 => Some(r#"Use a SIP Address that is not on a deny list."#),
            TwilioMiscellaneousError::ErrorCode19032 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode80105 => None,
            TwilioMiscellaneousError::ErrorCode32016 => Some(r#"* Check the dialed Number to ensure it is currently reachable.
* If you believe the Number is currently reachable, please reach out to Twilio Support through the [Console](https://console.twilio.com) or [Help Center](https://support.twilio.com) and be sure to mention this Error code."#),
            TwilioMiscellaneousError::ErrorCode13910 => None,
            TwilioMiscellaneousError::ErrorCode80407 => None,
            TwilioMiscellaneousError::ErrorCode13246 => None,
            TwilioMiscellaneousError::ErrorCode32103 => None,
            TwilioMiscellaneousError::ErrorCode70102 => None,
            TwilioMiscellaneousError::ErrorCode90032 => Some(r#"Use correct 'to' ("channel:address") for recipient object"#),
            TwilioMiscellaneousError::ErrorCode11236 => None,
            TwilioMiscellaneousError::ErrorCode14202 => None,
            TwilioMiscellaneousError::ErrorCode11216 => Some(r#"* Update your webhook configuration specifying the final URL you would like to be called, removing the need for redirects.
* Ensure you are using a standard redirect HTTP status code (301, 302, 303, or 307)
* Ensure that you are including a valid url in the location header of your response."#),
            TwilioMiscellaneousError::ErrorCode14111 => None,
            TwilioMiscellaneousError::ErrorCode70051 => Some(r#"* Make sure the account or the API key are valid and active
* If using a Restricted API Key - add the missing permission to the key
* If using a Restricted API Key - use a Main/Standard type API key"#),
            TwilioMiscellaneousError::ErrorCode21210 => Some(r#" [phone number verification on Console](https://www.twilio.com/console/phone-numbers/verified)"#),
            TwilioMiscellaneousError::ErrorCode80303 => None,
            TwilioMiscellaneousError::ErrorCode80905 => None,
            TwilioMiscellaneousError::ErrorCode61004 => None,
            TwilioMiscellaneousError::ErrorCode13217 => None,
            TwilioMiscellaneousError::ErrorCode80503 => None,
            TwilioMiscellaneousError::ErrorCode11320 => None,
            TwilioMiscellaneousError::ErrorCode13242 => None,
            TwilioMiscellaneousError::ErrorCode13245 => None,
            TwilioMiscellaneousError::ErrorCode51104 => None,
            TwilioMiscellaneousError::ErrorCode51122 => None,
            TwilioMiscellaneousError::ErrorCode20020 => Some(r#"* If data is needed to be updated in T-Mobile SDG Service Provisioning API the request must have updated fields"#),
            TwilioMiscellaneousError::ErrorCode19042 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode12101 => None,
            TwilioMiscellaneousError::ErrorCode14211 => None,
            TwilioMiscellaneousError::ErrorCode21452 => None,
            TwilioMiscellaneousError::ErrorCode61000 => None,
            TwilioMiscellaneousError::ErrorCode21421 => Some(r#"* For phone number lookup or purchase, please specify a valid phone number in E.164 format.
* For adding a Phone Number to a Messaging Service, verify that the Phone Number SID or Short Code SID is correct and formatted properly, then retry the request. "#),
            TwilioMiscellaneousError::ErrorCode13312 => None,
            TwilioMiscellaneousError::ErrorCode20429 => Some(r#"An API Request that receives an error 429 response is never processed and is always safe to retry.  Please wait for a short period of time and make the request again, or alter your client's settings to issue fewer concurrent requests to the Twilio API.

For more information, please review the 429 Error Response knowledge base article at [https://support.twilio.com/hc/en-us/articles/360044308153-Twilio-API-response-Error-429-Too-Many-Requests-](https://support.twilio.com/hc/en-us/articles/360044308153-Twilio-API-response-Error-429-Too-Many-Requests-)"#),
            TwilioMiscellaneousError::ErrorCode50068 => None,
            TwilioMiscellaneousError::ErrorCode51202 => None,
            TwilioMiscellaneousError::ErrorCode21471 => None,
            TwilioMiscellaneousError::ErrorCode70253 => None,
            TwilioMiscellaneousError::ErrorCode90012 => Some(r#"Split the broadcast to several parts where each part has smaller number of recipients than allowed"#),
            TwilioMiscellaneousError::ErrorCode21601 => None,
            TwilioMiscellaneousError::ErrorCode13221 => None,
            TwilioMiscellaneousError::ErrorCode14212 => None,
            TwilioMiscellaneousError::ErrorCode13251 => None,
            TwilioMiscellaneousError::ErrorCode51127 => None,
            TwilioMiscellaneousError::ErrorCode13299 => Some(r#"- "#),
            TwilioMiscellaneousError::ErrorCode403 => Some(r#"Verify credentials"#),
            TwilioMiscellaneousError::ErrorCode13231 => None,
            TwilioMiscellaneousError::ErrorCode13120 => None,
            TwilioMiscellaneousError::ErrorCode21653 => Some(r#"Fix the list of recipients according a channel restrictions"#),
            TwilioMiscellaneousError::ErrorCode12300 => Some(r#"* Verify that that your web server is returning a Content-Type and it is the expected value
* Make sure the URL noted refers to a valid resource
* Make sure messages to or from your Twilio phone number are using a supported content-type. See the [full list of supported content types](https://www.twilio.com/docs/sms/accepted-mime-types).
* Use one of the [supported request types](https://www.twilio.com/docs/runtime/functions/request-flow#supported-requests) to call a Twilio function."#),
            TwilioMiscellaneousError::ErrorCode51215 => None,
            TwilioMiscellaneousError::ErrorCode80604 => None,
            TwilioMiscellaneousError::ErrorCode32113 => Some(r#"* If your application can use a different header name, use an X- prefixed header name, e.g. if you want to use the name `Customer-Info`, see if your application can be configured to use `X-Customer-Info` instead."#),
            TwilioMiscellaneousError::ErrorCode21453 => None,
            TwilioMiscellaneousError::ErrorCode19024 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode11235 => None,
            TwilioMiscellaneousError::ErrorCode90025 => Some(r#"Check your template body has only data tags (placeholders)"#),
            TwilioMiscellaneousError::ErrorCode70106 => None,
            TwilioMiscellaneousError::ErrorCode10001 => Some(r#"*  Check your account balance.  Refill funds if necessary.	
*  Please reach out to Twilio Support through the [Console](https://console.twilio.com) or [Help Center](https://support.twilio.com)."#),
            TwilioMiscellaneousError::ErrorCode80605 => None,
            TwilioMiscellaneousError::ErrorCode13112 => None,
            TwilioMiscellaneousError::ErrorCode94100 => Some(r#"* Ensure that the callback URL specified is correct
* Ensure that your callback server can handle the request and responds with a 2xx HTTP status code"#),
            TwilioMiscellaneousError::ErrorCode90039 => Some(r#"Use correct http or https URL"#),
            TwilioMiscellaneousError::ErrorCode21209 => None,
            TwilioMiscellaneousError::ErrorCode11203 => None,
            TwilioMiscellaneousError::ErrorCode12100 => None,
            TwilioMiscellaneousError::ErrorCode61008 => None,
            TwilioMiscellaneousError::ErrorCode61005 => None,
            TwilioMiscellaneousError::ErrorCode14106 => None,
            TwilioMiscellaneousError::ErrorCode11217 => Some(r#"* Review the configured webhook URL to ensure that it is correct.
* Look for and fix errors in your server logs.
* Ensure that you can get 2xx status codes by calling your webhook URL.
* Review your proxy and authentication configurations.
* For rate limiting issues, consider shifting to Event Streams HTTP Sink which [support rate limiting](https://www.twilio.com/docs/events/faq/problems-on-delivery#what-does-throttle-sink-means-for-eventstreams)."#),
            TwilioMiscellaneousError::ErrorCode13248 => None,
            TwilioMiscellaneousError::ErrorCode94600 => Some(r#" * Use date filtering freely plus at most one other filter."#),
            TwilioMiscellaneousError::ErrorCode13244 => None,
            TwilioMiscellaneousError::ErrorCode51131 => None,
            TwilioMiscellaneousError::ErrorCode80902 => None,
            TwilioMiscellaneousError::ErrorCode21420 => None,
            TwilioMiscellaneousError::ErrorCode11237 => None,
            TwilioMiscellaneousError::ErrorCode61003 => None,
            TwilioMiscellaneousError::ErrorCode90022 => Some(r#"Use shorter 'TemplateArgs' dictionary values"#),
            TwilioMiscellaneousError::ErrorCode14108 => None,
            TwilioMiscellaneousError::ErrorCode20002 => None,
            TwilioMiscellaneousError::ErrorCode80406 => None,
            TwilioMiscellaneousError::ErrorCode21618 => None,
            TwilioMiscellaneousError::ErrorCode61007 => None,
            TwilioMiscellaneousError::ErrorCode19034 => Some(r#"Update the country code to match  ISO 3166-1 alpha-2 country code of the address format"#),
            TwilioMiscellaneousError::ErrorCode11770 => None,
            TwilioMiscellaneousError::ErrorCode60007 => Some(r#"- Ensure you have correctly enabled additional token validation at verification creation.
- Check App Security Token is being passed correctly as part of SNA URL validation."#),
            TwilioMiscellaneousError::ErrorCode11300 => None,
            TwilioMiscellaneousError::ErrorCode80307 => Some(r#"No action required."#),
            TwilioMiscellaneousError::ErrorCode21241 => Some(r#"* Remove the Credential List from any mapped SIP Domains before deleting."#),
            TwilioMiscellaneousError::ErrorCode19050 => Some(r#"Reach Customer Support or Try again later"#),
            TwilioMiscellaneousError::ErrorCode14105 => None,
            TwilioMiscellaneousError::ErrorCode80409 => None,
            TwilioMiscellaneousError::ErrorCode19025 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode404 => Some(r#"* Check that the specified resource still exists.
"#),
            TwilioMiscellaneousError::ErrorCode13110 => None,
            TwilioMiscellaneousError::ErrorCode11200 => Some(r#"* Double check that your TwiML URL does not return a 4xx or 5xx error
* Make certain that the URL does not perform a 302 redirect to an invalid URL
* Confirm the URL requested is not protected by HTTP Auth
* Make sure your web server allows HTTP POST requests to static resources (if the URL refers to .xml or .html files)
* Verify your web server is up and responsive
* Check to see that the URL host is not a private or local IP address
* Verify the ping times and packet loss between your web server and api.twilio.com
* Review firewall rules; modern web application firewalls can trigger on only a small subset of inbound connections leading to inconsistent behavior.
* Check logs at the very edge of your infrastructure to verify if TCP connection attempts are arriving at your edge. If you have confirmed these requests are not reaching your infrastructure, please reach out to [support](https://www.twilio.com/console/support/tickets/create).
* Use more robust options for webhook receipt. For inbound messages and calls be sure to provide a fallback URL (ideally on separate infrastructure). Transition integrations to [Event Streams](https://www.twilio.com/docs/events) which has various event sink types including webhooks with built in retries.
* Review your use of any [webhook connection overrides](https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides). In general the defaults provide the best results, start by reconfiguring your webhook URL without any fragment overrides and see if the problem persists.
* If synchronously processing a webhook requires significant time, we recommend that you simply acknowledge the event by quickly responding with an empty 202 (Accepted) and then processing the message on your own timeline. Replies to inbound message events can be done at any time by making a call to the REST API.
"#),
            TwilioMiscellaneousError::ErrorCode51111 => None,
            TwilioMiscellaneousError::ErrorCode21224 => None,
            TwilioMiscellaneousError::ErrorCode14203 => None,
            TwilioMiscellaneousError::ErrorCode60006 => Some(r#"- Check that the phone number provided is correct.
- If using Silent Network Auth, retry Verification using a channel not based on phone number such as email."#),
            TwilioMiscellaneousError::ErrorCode21479 => None,
            TwilioMiscellaneousError::ErrorCode21451 => None,
            TwilioMiscellaneousError::ErrorCode90011 => Some(r#"Use correct MessageSid. Example `SMec8e12b0a5eb4fc68e173f1c5db95b2a`"#),
            TwilioMiscellaneousError::ErrorCode21480 => None,
            TwilioMiscellaneousError::ErrorCode13322 => None,
            TwilioMiscellaneousError::ErrorCode13254 => None,
            TwilioMiscellaneousError::ErrorCode11251 => None,
            TwilioMiscellaneousError::ErrorCode70103 => None,
            TwilioMiscellaneousError::ErrorCode90034 => Some(r#"Use shorter url in 'BroadcastStatusCallbackUrl' field"#),
            TwilioMiscellaneousError::ErrorCode21212 => Some(r#"* Ensure your number is formatted in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
* Ensure that your `From` number is assigned and not on a do-not-originate (DNO) list.
* Ensure you are not using an [alphanumeric sender ID](https://www.twilio.com/docs/glossary/what-alphanumeric-sender-id) that is too generic (for example, "SMS" or "INFO").
* If you are getting this error when using a non-generic alphanumeric sender ID, please [submit a support ticket](https://www.twilio.com/console/support/tickets/create) for further assistance.
* If you are using an Alphanumeric Sender ID on a Trial Account, upgrade your account.
* If you are using a WhatsApp Sender, check that your [sender is approved](https://console.twilio.com/us1/develop/sms/senders/whatsapp-senders) and that you have followed the [onboarding instructions](https://www.twilio.com/docs/whatsapp/tutorial/requesting-access-to-whatsapp).
* If you are sending messages using a Messaging Service, and you wish to utilize an RCS Agent in your Sender Pool that falls back to SMS, [send the message from a MessagingServiceSid](https://www.twilio.com/docs/messaging/services#send-a-message-with-a-messaging-service-1). "#),
            TwilioMiscellaneousError::ErrorCode13210 => None,
            TwilioMiscellaneousError::ErrorCode11201 => None,
            TwilioMiscellaneousError::ErrorCode20413 => None,
            TwilioMiscellaneousError::ErrorCode12102 => None,
            TwilioMiscellaneousError::ErrorCode51001 => None,
            TwilioMiscellaneousError::ErrorCode84001 => Some(r#"- Define a timeout for async await events. "#),
            TwilioMiscellaneousError::ErrorCode90029 => Some(r#"Use not empty string as 'CorrelationId' field"#),
            TwilioMiscellaneousError::ErrorCode19040 => Some(r#"Use custom field definition API to define the custom field first"#),
            TwilioMiscellaneousError::ErrorCode32111 => Some(r#"* Ensure that your SIP URI is formed correctly. Header names should generally only consist of alphanumeric characters and hyphens."#),
            TwilioMiscellaneousError::ErrorCode90018 => Some(r#"Use shorter 'Template'"#),
            TwilioMiscellaneousError::ErrorCode94001 => Some(r#"* Ensure that the transcribe value is set to “true” to request a transcription via REST API or TwiML"#),
            TwilioMiscellaneousError::ErrorCode94201 => Some(r#"* Specify a encryptionKeySid of a valid credential resource of type Public Key that can be used to encrypt transcription results or disable encryption"#),
            TwilioMiscellaneousError::ErrorCode13253 => None,
            TwilioMiscellaneousError::ErrorCode19004 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode19005 => Some(r#"Review the request body and the API documentation for more information"#),
            TwilioMiscellaneousError::ErrorCode90019 => Some(r#"Use shorter 'TemplateArgs' dictionary"#),
            TwilioMiscellaneousError::ErrorCode400 => Some(r#"* Retry the request after confirming the request is valid.
* Verify if the resource to be modified exists and is in a valid state."#),
            TwilioMiscellaneousError::ErrorCode13520 => None,
            TwilioMiscellaneousError::ErrorCode21609 => None,
            TwilioMiscellaneousError::ErrorCode51121 => None,
            TwilioMiscellaneousError::ErrorCode84002 => Some(r#"- Check error payload for the error message."#),
            TwilioMiscellaneousError::ErrorCode11310 => None,
            TwilioMiscellaneousError::ErrorCode60008 => Some(r#"- Complete the [Account Security Registration](https://interactive.twilio.com/account-security-registration-form?_ga=2.40477419.894088021.1660748067-1879743973.1650468405) form to use this carrier.
- If you have completed the Account Security Registration form, [contact Twilio Support](https://www.twilio.com/help/contact) to confirm that you are approved.
- If you have completed the Account Security Registration form and it has been approved, [contact Twilio Support](https://www.twilio.com/help/contact) to rule out integration issues.
- If using Silent Network Auth, retry Verification using a channel other than Silent Network Auth for this end user."#),
            TwilioMiscellaneousError::ErrorCode94300 => Some(r#"* Callback "Url" value should be valid Http(s) url format 
* Callback "Method" value should be either POST or GET 
* Disable callback by setting “Url” to ‘’ value (empty string)"#),
            TwilioMiscellaneousError::ErrorCode51112 => None,
            TwilioMiscellaneousError::ErrorCode94301 => Some(r#"* Specify a valid "UniqueName" for transcription configuration"#),
            TwilioMiscellaneousError::ErrorCode20005 => None,
            TwilioMiscellaneousError::ErrorCode32110 => Some(r#"* If you specify SIP headers in your URI, ensure any non-alphanumeric characters in the header values are escaped. For example, to add a User-to-User header with value `0A1B2C3D;encoding=hex`, you must encode this into the URI as `User-to-User=0A1B2C3D%3Bencoding%3Dhex`."#),
            TwilioMiscellaneousError::ErrorCode51120 => None,
            TwilioMiscellaneousError::ErrorCode21230 => None,
            TwilioMiscellaneousError::ErrorCode90038 => Some(r#"Use valid http or https url"#),
            TwilioMiscellaneousError::ErrorCode21214 => None,
            TwilioMiscellaneousError::ErrorCode51007 => Some(r#"For further assistance, please reach out to Twilio Support through the [Console](https://console.twilio.com) or [Help Center](https://support.twilio.com)."#),
            TwilioMiscellaneousError::ErrorCode80603 => Some(r#"Retry with a UniqueName that is not currently in use by any other Sessions for this Service."#),
            TwilioMiscellaneousError::ErrorCode90026 => Some(r#"Check your template body is correct Mustache grammar."#),
            TwilioMiscellaneousError::ErrorCode13224 => Some(r#"Use E.164 formatting and ensure the destination is a valid, in-service destination."#),
            TwilioMiscellaneousError::ErrorCode14206 => None,
            TwilioMiscellaneousError::ErrorCode94604 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode11241 => Some(r#"* Correct the 'e' parameter in the fragment part of the URL, the one after '#'."#),
            TwilioMiscellaneousError::ErrorCode13237 => None,
            TwilioMiscellaneousError::ErrorCode80405 => None,
            TwilioMiscellaneousError::ErrorCode21474 => None,
            TwilioMiscellaneousError::ErrorCode13250 => None,
            TwilioMiscellaneousError::ErrorCode13314 => None,
            TwilioMiscellaneousError::ErrorCode50069 => None,
            TwilioMiscellaneousError::ErrorCode51119 => None,
            TwilioMiscellaneousError::ErrorCode80610 => None,
            TwilioMiscellaneousError::ErrorCode21213 => None,
            TwilioMiscellaneousError::ErrorCode90036 => Some(r#"Use shorter 'body' value for recipient object"#),
            TwilioMiscellaneousError::ErrorCode13211 => None,
            TwilioMiscellaneousError::ErrorCode51005 => None,
            TwilioMiscellaneousError::ErrorCode12400 => None,
            TwilioMiscellaneousError::ErrorCode32114 => Some(r#"* Check the other details of the debugger alert. The alert may indicate which parameter contains the unsupported value.
* Update your application/configuration to ensure a URI with appropriate parameters is sent."#),
            TwilioMiscellaneousError::ErrorCode21450 => None,
            TwilioMiscellaneousError::ErrorCode21454 => None,
            TwilioMiscellaneousError::ErrorCode21626 => None,
            TwilioMiscellaneousError::ErrorCode13410 => None,
            TwilioMiscellaneousError::ErrorCode21401 => Some(r#"Try using a different phone number: https://www.twilio.com/phone-numbers"#),
            TwilioMiscellaneousError::ErrorCode70153 => None,
            TwilioMiscellaneousError::ErrorCode70152 => None,
            TwilioMiscellaneousError::ErrorCode80202 => None,
            TwilioMiscellaneousError::ErrorCode20503 => None,
            TwilioMiscellaneousError::ErrorCode94000 => Some(r#" "#),
            TwilioMiscellaneousError::ErrorCode13232 => None,
            TwilioMiscellaneousError::ErrorCode21901 => Some(r#"Use correct DltTemplateId"#),
            TwilioMiscellaneousError::ErrorCode19013 => Some(r#"Contact should contain at least one of the following fields - first_name, middle_name, last_name, legal_name, preferred_name, unique_customer_provided_id or channel"#),
            TwilioMiscellaneousError::ErrorCode10004 => Some(r#"[Upgrade your account](https://www.twilio.com/docs/usage/tutorials/how-to-use-your-free-trial-account-namer#how-to-upgrade-your-account) and [create a Primary Business Profile](https://www.twilio.com/docs/trust-hub/trusthub-rest-api/console-create-a-primary-customer-profile) to remove concurrent call limitations."#),
            TwilioMiscellaneousError::ErrorCode19037 => Some(r#"When updating a location at least one field should be updated"#),
            TwilioMiscellaneousError::ErrorCode13213 => None,
            TwilioMiscellaneousError::ErrorCode11205 => Some(r#"*  Verify the URL provided is accessible to the public internet.	
*  Verify network connectivity to your web server.
*  Check your TCP logs to verify inbound connection attempts are successful.
*  Check HTTP server logs to verify a response was generated and returned within the timeout.
*  Check your edge element logs to verify responses are making it out of your infrastructure."#),
            TwilioMiscellaneousError::ErrorCode51102 => None,
            TwilioMiscellaneousError::ErrorCode51129 => None,
            TwilioMiscellaneousError::ErrorCode14223 => None,
            TwilioMiscellaneousError::ErrorCode410 => Some(r#"* Do not retry the request since the condition is likely permanent.
"#),
            TwilioMiscellaneousError::ErrorCode94602 => Some(r#" * FromDate should be earlier than the present date."#),
            TwilioMiscellaneousError::ErrorCode20003 => Some(r#"* Verify the Account SID and Auth Token are correct
* Verify the correct Account is being accessed
* Ensure the Account is active, not suspended or closed
* Ensure no extra characters or spaces are being included
* Ensure JWT is only used with API Key
* Ensure the API Key's Twilio Region matches the request's specified Twilio Region"#),
            TwilioMiscellaneousError::ErrorCode80701 => None,
            TwilioMiscellaneousError::ErrorCode21217 => None,
            TwilioMiscellaneousError::ErrorCode21621 => Some(r#"* Buy an MMS Capable phone number from the [Twilio Console](https://console.twilio.com/us1/develop/phone-numbers/manage/search?isoCountry=US&types[]=Local&types[]=Tollfree&capabilities[]=Sms&capabilities[]=Mms&capabilities[]=Voice&capabilities[]=Fax&searchTerm=&searchFilter=left&searchType=number) by filtering for “MMS” under “Capabilities”.
* Check if you already have MMS capable numbers in the [Twilio Console](https://console.twilio.com/us1/develop/phone-numbers/manage/incoming) and use that number in your `From` parameter or Messaging Service."#),
            TwilioMiscellaneousError::ErrorCode13249 => None,
            TwilioMiscellaneousError::ErrorCode13215 => None,
            TwilioMiscellaneousError::ErrorCode21202 => None,
            TwilioMiscellaneousError::ErrorCode21225 => None,
            TwilioMiscellaneousError::ErrorCode21455 => None,
            TwilioMiscellaneousError::ErrorCode94101 => Some(r#"* Ensure that your callback server can handle the request and responds within a reasonable time"#),
            TwilioMiscellaneousError::ErrorCode13235 => None,
            TwilioMiscellaneousError::ErrorCode51128 => None,
            TwilioMiscellaneousError::ErrorCode13236 => None,
            TwilioMiscellaneousError::ErrorCode21405 => None,
            TwilioMiscellaneousError::ErrorCode70002 => None,
            TwilioMiscellaneousError::ErrorCode21223 => None,
            TwilioMiscellaneousError::ErrorCode21900 => Some(r#"Use correct DltPEId"#),
            TwilioMiscellaneousError::ErrorCode15003 => Some(r#"Ensure your application responds to callbacks with: 

*  200 OK  
*  Content-Type: text/xml 
*  Valid TwiML

Or respond with 204 No Content and an empty response body."#),
            TwilioMiscellaneousError::ErrorCode19003 => Some(r#"Provide different unique_customer_provided_id or remove the existing one"#),
            TwilioMiscellaneousError::ErrorCode15000 => None,
            TwilioMiscellaneousError::ErrorCode21240 => Some(r#"* Ensure that your Credential List meets the validation requirements."#),
            TwilioMiscellaneousError::ErrorCode21206 => None,
            TwilioMiscellaneousError::ErrorCode70053 => None,
            TwilioMiscellaneousError::ErrorCode80205 => None,
            TwilioMiscellaneousError::ErrorCode21228 => None,
            TwilioMiscellaneousError::ErrorCode21232 => None,
            TwilioMiscellaneousError::ErrorCode91202 => Some(r#"* Recheck to see if the correct information is provided else
* Recheck to verify is the resource actually exists"#),
            TwilioMiscellaneousError::ErrorCode51103 => None,
            TwilioMiscellaneousError::ErrorCode80908 => None,
            TwilioMiscellaneousError::ErrorCode80601 => None,
            TwilioMiscellaneousError::ErrorCode13710 => None,
            TwilioMiscellaneousError::ErrorCode14104 => None,
            TwilioMiscellaneousError::ErrorCode80402 => None,
            TwilioMiscellaneousError::ErrorCode90020 => Some(r#"Do not use empty or blank keys in 'TemplateArgs' dictionary"#),
            TwilioMiscellaneousError::ErrorCode21221 => None,
            TwilioMiscellaneousError::ErrorCode20001 => None,
            TwilioMiscellaneousError::ErrorCode90028 => Some(r#"Use shorter string lenght for 'IdempotencyToken' field"#),
            TwilioMiscellaneousError::ErrorCode30014 => None,
            TwilioMiscellaneousError::ErrorCode21100 => None,
            TwilioMiscellaneousError::ErrorCode21476 => None,
            TwilioMiscellaneousError::ErrorCode20426 => None,
            TwilioMiscellaneousError::ErrorCode90033 => Some(r#"Use correct channel type (sms|mms|etc) and appropriate address"#),
            TwilioMiscellaneousError::ErrorCode20009 => Some(r#"* If you are attempting to delete a call, verify that the call is not still in-progress.
* If you are attempting to delete a call or message shortly after sending or receiving it, please wait at least 1 minute to make your DELETE request. If you receive this error after waiting 1 minute, wait several minutes and retry deletion again.
* If you encounter this issue frequently even when waiting several minutes before deleting a message or a completed call, please [contact Twilio support](https://www.twilio.com/console/support/tickets/create) with examples of affected Call or Message SIDs.
* For the highest level of privacy for Twilio SMS messages, apply for [message redaction](https://ahoy.twilio.com/message-redaction) which can automatically redact message bodies or phone numbers immediately after a message is sent or received."#),
            TwilioMiscellaneousError::ErrorCode94302 => Some(r#"* Specify a valid "UniqueName" for transcription configuration"#),
            TwilioMiscellaneousError::ErrorCode13613 => None,
            TwilioMiscellaneousError::ErrorCode11210 => Some(r#"* Verify the hostname of the URL has a valid DNS record the can be resolved by the public"#),
            TwilioMiscellaneousError::ErrorCode21219 => None,
            TwilioMiscellaneousError::ErrorCode21404 => None,
            TwilioMiscellaneousError::ErrorCode21622 => None,
            TwilioMiscellaneousError::ErrorCode61002 => None,
            TwilioMiscellaneousError::ErrorCode20008 => None,
            TwilioMiscellaneousError::ErrorCode51115 => None,
            TwilioMiscellaneousError::ErrorCode61006 => None,
            TwilioMiscellaneousError::ErrorCode20010 => None,
            TwilioMiscellaneousError::ErrorCode84003 => Some(r#"- Check the liquid expressions in the block evaluate to a proper value."#),
            TwilioMiscellaneousError::ErrorCode21208 => None,
            TwilioMiscellaneousError::ErrorCode21200 => None,
            TwilioMiscellaneousError::ErrorCode90023 => Some(r#"Do not use null 'TemplateArgs' dictionary values"#),
            TwilioMiscellaneousError::ErrorCode90035 => Some(r#"Use shorter url in 'MessageStatusCallbackUrl' field"#),
            TwilioMiscellaneousError::ErrorCode80609 => None,
            TwilioMiscellaneousError::ErrorCode51124 => None,
            TwilioMiscellaneousError::ErrorCode70005 => None,
            TwilioMiscellaneousError::ErrorCode14205 => None,
            TwilioMiscellaneousError::ErrorCode80408 => None,
            TwilioMiscellaneousError::ErrorCode13243 => None,
            TwilioMiscellaneousError::ErrorCode21238 => Some(r#"* Ensure that you are creating a valid Address."#),
            TwilioMiscellaneousError::ErrorCode13320 => None,
            TwilioMiscellaneousError::ErrorCode30015 => None,
            TwilioMiscellaneousError::ErrorCode50353 => Some(r#"Provide non-existing Conversation unique name in the request."#),
            TwilioMiscellaneousError::ErrorCode21458 => None,
            TwilioMiscellaneousError::ErrorCode14201 => None,
            TwilioMiscellaneousError::ErrorCode70101 => None,
            TwilioMiscellaneousError::ErrorCode21243 => Some(r#"* Please see the response body for more details."#),
            TwilioMiscellaneousError::ErrorCode51123 => None,
            TwilioMiscellaneousError::ErrorCode20023 => Some(r#"* Check the phone number"#),
            TwilioMiscellaneousError::ErrorCode70151 => None,
            TwilioMiscellaneousError::ErrorCode51002 => None,
            TwilioMiscellaneousError::ErrorCode80102 => None,
            TwilioMiscellaneousError::ErrorCode70003 => None,
            TwilioMiscellaneousError::ErrorCode90024 => Some(r#"Check all tags from template body are specified in 'TemplateArgs' dictionary as keys"#),
            TwilioMiscellaneousError::ErrorCode13255 => None,
            TwilioMiscellaneousError::ErrorCode14215 => None,
            TwilioMiscellaneousError::ErrorCode14102 => None,
            TwilioMiscellaneousError::ErrorCode12200 => Some(r#"* Check the line and column reported by the warning to see what part of your XML response caused the complaint
* Verify that your application server is accepting and properly responding to any [custom parameters](https://support.twilio.com/hc/en-us/articles/115011213347) you may be passing"#),
            TwilioMiscellaneousError::ErrorCode94501 => Some(r#" * Value must be enqueued, processing, completed, failed or deleted."#),
            TwilioMiscellaneousError::ErrorCode80907 => None,
            TwilioMiscellaneousError::ErrorCode61009 => None,
            TwilioMiscellaneousError::ErrorCode20006 => None,
            TwilioMiscellaneousError::ErrorCode14110 => None,
            TwilioMiscellaneousError::ErrorCode80104 => None,
            TwilioMiscellaneousError::ErrorCode11215 => None,
            TwilioMiscellaneousError::ErrorCode14210 => None,
            TwilioMiscellaneousError::ErrorCode21205 => None,
            TwilioMiscellaneousError::ErrorCode19036 => Some(r#"Page token must be an integer"#),
            TwilioMiscellaneousError::ErrorCode60001 => Some(r#"- Check that the Account SID provided is correct.
- [Contact Twilio Support](https://www.twilio.com/help/contact) to confirm that access to this endpoint is enabled for the given Account SID."#),
            TwilioMiscellaneousError::ErrorCode70154 => None,
            TwilioMiscellaneousError::ErrorCode14103 => None,
            TwilioMiscellaneousError::ErrorCode13201 => None,
            TwilioMiscellaneousError::ErrorCode13311 => None,
            TwilioMiscellaneousError::ErrorCode11240 => Some(r#"* Correct the 'e' parameter in the fragment part of the URL, the one after '#'."#),
            TwilioMiscellaneousError::ErrorCode11220 => Some(r#"*  Verify cipher suites in-use are up to date. Twilio-supported ciphers can be found [here](https://support.twilio.com/hc/en-us/articles/360007724794-Notice-Twilio-REST-API-s-TLS-and-Cipher-Suite-Security-Changes-for-June-2019)
*  Use compatible version of TLS, Twilio supports TLS 1.2."#),
            TwilioMiscellaneousError::ErrorCode21470 => None,
            TwilioMiscellaneousError::ErrorCode19020 => Some(r#"Channel value has to be unique for contact, use different channel value or update the existing one"#),
            TwilioMiscellaneousError::ErrorCode30013 => None,
            TwilioMiscellaneousError::ErrorCode51101 => None,
            TwilioMiscellaneousError::ErrorCode94603 => Some(r#" * Ttl value must be between 1 and 3600 seconds"#),
            TwilioMiscellaneousError::ErrorCode51117 => None,
            TwilioMiscellaneousError::ErrorCode21617 => Some(r#"An online text to byte calculator can help you understand if certain characters are taking up more character space than others."#),
            TwilioMiscellaneousError::ErrorCode90040 => Some(r#"Use fewer 'MediaUrl' fields in Broadcast request"#),
            TwilioMiscellaneousError::ErrorCode90021 => Some(r#"Use shorter 'TemplateArgs' dictionary keys"#),
            TwilioMiscellaneousError::ErrorCode84000 => Some(r#"Reduce the number of steps in your flow."#),
            TwilioMiscellaneousError::ErrorCode80401 => None,
            TwilioMiscellaneousError::ErrorCode13325 => None
        }
    }
}
