// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioProgrammableChatError;
use standard_error::traits::StandardErrorCausesTrait;

impl StandardErrorCausesTrait for TwilioProgrammableChatError {
    fn causes(&self) -> Option<&'static str> {
        match self {
            TwilioProgrammableChatError::ErrorCode50304 => None,
            TwilioProgrammableChatError::ErrorCode50412 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50417 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50208 => None,
            TwilioProgrammableChatError::ErrorCode50052 => None,
            TwilioProgrammableChatError::ErrorCode50205 => None,
            TwilioProgrammableChatError::ErrorCode50207 => None,
            TwilioProgrammableChatError::ErrorCode50054 => None,
            TwilioProgrammableChatError::ErrorCode50074 => Some(r#"*  Your application is generating too many actions per second (APS) for Chat service instance either to a specific Chat API endpoint or across different Chat API endpoints
*  Note that the APS limit is enforced for commands such as sending a Message or creating a Channel - not Read actions"#),
            TwilioProgrammableChatError::ErrorCode50384 => Some(r#"* 'State' parameter value is set to 'closed' which is not allowed during conversation creation"#),
            TwilioProgrammableChatError::ErrorCode50434 => Some(r#"* You may have inadvertently provided an Identity (chat user), rather than an Address (mobile phone).
* You may have mistyped or inadvertently left out the ProjectedAddress parameter."#),
            TwilioProgrammableChatError::ErrorCode50509 => None,
            TwilioProgrammableChatError::ErrorCode50077 => Some(r#"*  Provided url has the wrong format. "#),
            TwilioProgrammableChatError::ErrorCode50451 => Some(r#"*  Both Identity and Address were provided"#),
            TwilioProgrammableChatError::ErrorCode50059 => None,
            TwilioProgrammableChatError::ErrorCode50431 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50375 => Some(r#"* 'TimeToInactive' field is set to duration which is less than 1 minute."#),
            TwilioProgrammableChatError::ErrorCode50380 => Some(r#"* 'TimeToClosed' parameter value is not ISO8601 duration."#),
            TwilioProgrammableChatError::ErrorCode50449 => Some(r#"* You might be adding a new channel to the service instance while the channel with the same unique name is being removed from another thread.
* You might be submitting multiple concurrent requests to add a channel with the same unique name to the service instance.
* You might be submitting multiple concurrent requests to delete the same channel by SID or unique name from the service instance."#),
            TwilioProgrammableChatError::ErrorCode50057 => None,
            TwilioProgrammableChatError::ErrorCode50340 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50377 => Some(r#"* Conversation state is set manually or by timer to 'closed' which means that conversation can't be updated anymore."#),
            TwilioProgrammableChatError::ErrorCode50506 => None,
            TwilioProgrammableChatError::ErrorCode50101 => None,
            TwilioProgrammableChatError::ErrorCode50332 => None,
            TwilioProgrammableChatError::ErrorCode50393 => Some(r#"*  No Type parameter provided
*  Provided Type parameter not equal to 'private'"#),
            TwilioProgrammableChatError::ErrorCode50436 => Some(r#"* You may have failed to remove old participants in a long-running conversation.
* You may have reached an edge-case in your application that creates unusually large conversations, in excess of the limit."#),
            TwilioProgrammableChatError::ErrorCode50374 => Some(r#"* 'State' field is set to empty string value when channel has some non-empty state."#),
            TwilioProgrammableChatError::ErrorCode50330 => None,
            TwilioProgrammableChatError::ErrorCode50382 => Some(r#"* 'State' parameter is missing while 'TimeToInactive' and/or 'TimeToClosed' are present"#),
            TwilioProgrammableChatError::ErrorCode50418 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50378 => Some(r#"* 'State' parameter value is set to values different from 'active', 'inactive', 'closed'."#),
            TwilioProgrammableChatError::ErrorCode50438 => Some(r#"* You previously created a conflicting conversation
* Twilio created a conversation — which now conflicts — in the course of Autocreation."#),
            TwilioProgrammableChatError::ErrorCode50107 => None,
            TwilioProgrammableChatError::ErrorCode50201 => None,
            TwilioProgrammableChatError::ErrorCode50328 => None,
            TwilioProgrammableChatError::ErrorCode50104 => None,
            TwilioProgrammableChatError::ErrorCode50309 => Some(r#"*  Request does not contain correctly formatted parameter for Date Updated."#),
            TwilioProgrammableChatError::ErrorCode50363 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50414 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50310 => None,
            TwilioProgrammableChatError::ErrorCode50371 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50373 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50442 => Some(r#"* The participant does not have the projected address you are trying to remove."#),
            TwilioProgrammableChatError::ErrorCode50370 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50511 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50327 => None,
            TwilioProgrammableChatError::ErrorCode50211 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50602 => Some(r#"User was added directly to the channel and his invite was removed so he can't decline it."#),
            TwilioProgrammableChatError::ErrorCode50437 => Some(r#"* An participant with the same ProxyAddress+Address pair already exists in this conversation
* A native GMMS Participant with the same Address exists in this conversation
* A Chat Participant with the same Identity and Project Address exists in this conversation

This error may result from a race condition, where a participant was inadvertently added twice."#),
            TwilioProgrammableChatError::ErrorCode50051 => None,
            TwilioProgrammableChatError::ErrorCode50408 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50440 => Some(r#"* The participant does not have a proxy address you are trying to remove.
* The participant you are updating is not an SMS participant."#),
            TwilioProgrammableChatError::ErrorCode50351 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50213 => Some(r#"* You might be adding a new user to the service instance while the user with the same identity is being removed from another thread.
* You might be submitting multiple concurrent requests to add a user with the same identity to the service instance.
* You might be submitting multiple concurrent requests to delete the same user by SID or identity from the service instance."#),
            TwilioProgrammableChatError::ErrorCode50100 => None,
            TwilioProgrammableChatError::ErrorCode50369 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50516 => Some(r#"* Some text or message sid was provided as message index"#),
            TwilioProgrammableChatError::ErrorCode50204 => None,
            TwilioProgrammableChatError::ErrorCode50416 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50053 => None,
            TwilioProgrammableChatError::ErrorCode50513 => Some(r#"* Provided author Address is not among Group MMS participants.
* Provided author Identity is not among Group MMS participants."#),
            TwilioProgrammableChatError::ErrorCode50419 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50413 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50362 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50320 => None,
            TwilioProgrammableChatError::ErrorCode50202 => None,
            TwilioProgrammableChatError::ErrorCode50105 => None,
            TwilioProgrammableChatError::ErrorCode50058 => None,
            TwilioProgrammableChatError::ErrorCode50422 => Some(r#"You are trying to add more non-chat participants than allowed in this conversation. Maximum number of conversation participants is 50.
* You are trying to add more non-Chat participants than allowed in this conversation. [Maximum number](https://www.twilio.com/docs/conversations/conversations-limits) of conversation participants is 50."#),
            TwilioProgrammableChatError::ErrorCode50003 => None,
            TwilioProgrammableChatError::ErrorCode50324 => None,
            TwilioProgrammableChatError::ErrorCode50421 => Some(r#"Request does not contain correctly formatted parameter for last read message index"#),
            TwilioProgrammableChatError::ErrorCode50361 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50364 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50415 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50212 => Some(r#"User with specified Identity already invited to this Channel."#),
            TwilioProgrammableChatError::ErrorCode50600 => None,
            TwilioProgrammableChatError::ErrorCode50203 => None,
            TwilioProgrammableChatError::ErrorCode50056 => None,
            TwilioProgrammableChatError::ErrorCode50403 => None,
            TwilioProgrammableChatError::ErrorCode50420 => Some(r#"Participant is being created with not supported MessagingBinding parameters. Sms Participant should not have MessagingBinding.Name or MessagingBinding.Level."#),
            TwilioProgrammableChatError::ErrorCode50321 => None,
            TwilioProgrammableChatError::ErrorCode50502 => None,
            TwilioProgrammableChatError::ErrorCode19038 => Some(r#"Get chat messages PageToken is smaller than 0"#),
            TwilioProgrammableChatError::ErrorCode50401 => None,
            TwilioProgrammableChatError::ErrorCode50507 => None,
            TwilioProgrammableChatError::ErrorCode50206 => None,
            TwilioProgrammableChatError::ErrorCode50435 => Some(r#"* The conversation does not have at least three participants with messaging binding.
* The conversation has got a participant with identity but without projected address.
* The conversation's participants do not make a valid address list for group messaging."#),
            TwilioProgrammableChatError::ErrorCode50303 => None,
            TwilioProgrammableChatError::ErrorCode50078 => Some(r#"*  Provided url has the wrong format."#),
            TwilioProgrammableChatError::ErrorCode50379 => Some(r#"* 'TimeToInactive' parameter value is not ISO8601 duration."#),
            TwilioProgrammableChatError::ErrorCode50350 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50060 => None,
            TwilioProgrammableChatError::ErrorCode50331 => None,
            TwilioProgrammableChatError::ErrorCode50329 => None,
            TwilioProgrammableChatError::ErrorCode50441 => Some(r#"* The participant to which you are trying to add a proxy address, does not have a user address."#),
            TwilioProgrammableChatError::ErrorCode50391 => Some(r#"* You might be adding a new conversation to the service instance while the conversation with the same unique name is being removed from another thread.
* You might be submitting multiple concurrent requests to add a conversation with the same unique name to the service instance.
* You might be submitting multiple concurrent requests to delete the same conversation by SID or unique name from the service instance."#),
            TwilioProgrammableChatError::ErrorCode50106 => None,
            TwilioProgrammableChatError::ErrorCode50368 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50214 => Some(r#"User has joined too many conversations"#),
            TwilioProgrammableChatError::ErrorCode50512 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50326 => None,
            TwilioProgrammableChatError::ErrorCode50405 => None,
            TwilioProgrammableChatError::ErrorCode50006 => Some(r#"Account SID in request does not match pattern "AC[0-9a-f]{32}"."#),
            TwilioProgrammableChatError::ErrorCode50209 => None,
            TwilioProgrammableChatError::ErrorCode50306 => None,
            TwilioProgrammableChatError::ErrorCode50508 => None,
            TwilioProgrammableChatError::ErrorCode20161 => Some(r#"* You may have passed parameters, but named them incorrectly.
* You may have forgotten to pass form-encoded parameters with your request"#),
            TwilioProgrammableChatError::ErrorCode50400 => None,
            TwilioProgrammableChatError::ErrorCode50341 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50407 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50433 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50200 => None,
            TwilioProgrammableChatError::ErrorCode50402 => None,
            TwilioProgrammableChatError::ErrorCode50432 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50367 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50055 => None,
            TwilioProgrammableChatError::ErrorCode50061 => None,
            TwilioProgrammableChatError::ErrorCode50004 => None,
            TwilioProgrammableChatError::ErrorCode50610 => Some(r#"The Twilio phone number associated with the address configuration was either released or ported out"#),
            TwilioProgrammableChatError::ErrorCode50305 => None,
            TwilioProgrammableChatError::ErrorCode50322 => None,
            TwilioProgrammableChatError::ErrorCode50334 => Some(r#"* Your API request tried to update the channel while the channel deletion operation was in progress."#),
            TwilioProgrammableChatError::ErrorCode50406 => None,
            TwilioProgrammableChatError::ErrorCode50050 => None,
            TwilioProgrammableChatError::ErrorCode50349 => Some(r#"* You might be adding a new channel to the service instance while the channel with the same unique name is being removed from another thread.
* You might be submitting multiple concurrent requests to add a channel with the same unique name to the service instance.
* You might be submitting multiple concurrent requests to delete the same channel by SID or unique name from the service instance."#),
            TwilioProgrammableChatError::ErrorCode50503 => None,
            TwilioProgrammableChatError::ErrorCode50109 => Some(r#"Specified Conversation Role does not exist."#),
            TwilioProgrammableChatError::ErrorCode50065 => None,
            TwilioProgrammableChatError::ErrorCode50443 => Some(r#"* You are trying to add a projected address to a participant with messaging binding assigned."#),
            TwilioProgrammableChatError::ErrorCode50342 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50076 => Some(r#"*  Application side processing is exceeding 5 seconds.
*  Some network blips might cause delay in returning the response to chat"#),
            TwilioProgrammableChatError::ErrorCode50390 => Some(r#"Specified Conversation's Unique Name matches Conversation SID Pattern "CH[0-9a-f]{32}"."#),
            TwilioProgrammableChatError::ErrorCode50376 => Some(r#"* 'TimeToClosed' field is set to duration which is less than 10 minutes."#),
            TwilioProgrammableChatError::ErrorCode50366 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50392 => Some(r#"* 'PreWebhookTimeout' field is set with a value less than or equal to 0."#),
            TwilioProgrammableChatError::ErrorCode50500 => None,
            TwilioProgrammableChatError::ErrorCode50002 => None,
            TwilioProgrammableChatError::ErrorCode50308 => None,
            TwilioProgrammableChatError::ErrorCode50103 => None,
            TwilioProgrammableChatError::ErrorCode50504 => Some(r#"Message body parameter is too long. Visit the [Chat Limits](https://www.twilio.com/docs/chat/chat-limits) documentation to learn more about the maximum message length. "#),
            TwilioProgrammableChatError::ErrorCode50307 => None,
            TwilioProgrammableChatError::ErrorCode50300 => None,
            TwilioProgrammableChatError::ErrorCode50409 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50325 => None,
            TwilioProgrammableChatError::ErrorCode50404 => None,
            TwilioProgrammableChatError::ErrorCode50323 => None,
            TwilioProgrammableChatError::ErrorCode50063 => None,
            TwilioProgrammableChatError::ErrorCode50360 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50444 => Some(r#"* You are trying to add an identity to a participant with identity already assigned.
* You are trying to add an identity to a participant without projected address."#),
            TwilioProgrammableChatError::ErrorCode50302 => None,
            TwilioProgrammableChatError::ErrorCode50102 => None,
            TwilioProgrammableChatError::ErrorCode50411 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50372 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50430 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50000 => None,
            TwilioProgrammableChatError::ErrorCode50601 => None,
            TwilioProgrammableChatError::ErrorCode50439 => Some(r#"* The account does not own the Address (eg. phone number) used as a Projected Address."#),
            TwilioProgrammableChatError::ErrorCode50510 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50347 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50210 => None,
            TwilioProgrammableChatError::ErrorCode50501 => None,
            TwilioProgrammableChatError::ErrorCode50001 => None,
            TwilioProgrammableChatError::ErrorCode50505 => None,
            TwilioProgrammableChatError::ErrorCode50365 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50301 => None,
            TwilioProgrammableChatError::ErrorCode50385 => Some(r#"* You may be using a Programmable Chat service that in the ie1 region (at chat.ie1.twilio.com). While Conversations is backwards compatible with Chat in other respects, the product presently works only in the default region (US East).
* You may have inadvertently specified a region (other than the default) in your Conversations SDKs."#)
        }
    }
}
