// AUTO-GENERATED. DO NOT MODIFY. YOUR CHANGES WILL BE OVER-WRITTEN
use crate::products::TwilioProgrammableChatError;
use standard_error::traits::StandardErrorDescriptionTrait;

impl StandardErrorDescriptionTrait for TwilioProgrammableChatError {
    fn description(&self) -> Option<&'static str> {
        match self {
            TwilioProgrammableChatError::ErrorCode50304 => None,
            TwilioProgrammableChatError::ErrorCode50412 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50417 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50208 => None,
            TwilioProgrammableChatError::ErrorCode50052 => None,
            TwilioProgrammableChatError::ErrorCode50205 => None,
            TwilioProgrammableChatError::ErrorCode50207 => None,
            TwilioProgrammableChatError::ErrorCode50054 => None,
            TwilioProgrammableChatError::ErrorCode50074 => None,
            TwilioProgrammableChatError::ErrorCode50384 => Some(r#"You are trying to set 'closed' state during conversation creation which is not allowed"#),
            TwilioProgrammableChatError::ErrorCode50434 => Some(r#"This is a Group MMS conversation, but the given participant has neither an Address nor a ProjectedAddress."#),
            TwilioProgrammableChatError::ErrorCode50509 => None,
            TwilioProgrammableChatError::ErrorCode50077 => None,
            TwilioProgrammableChatError::ErrorCode50451 => None,
            TwilioProgrammableChatError::ErrorCode50059 => None,
            TwilioProgrammableChatError::ErrorCode50431 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50375 => Some(r#"'TimeToInactive' duration should be greater or equal to 1 minute."#),
            TwilioProgrammableChatError::ErrorCode50380 => Some(r#"'TimeToClosed' parameter supported values are ISO8601 durations."#),
            TwilioProgrammableChatError::ErrorCode50449 => Some(r#"The requested channel is already being added or removed from this service instance concurrently with another API request. The last request will be rejected to avoid inconsistent state."#),
            TwilioProgrammableChatError::ErrorCode50057 => None,
            TwilioProgrammableChatError::ErrorCode50340 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50377 => Some(r#"Conversation state is 'closed' so it can't be used for chatting anymore."#),
            TwilioProgrammableChatError::ErrorCode50506 => None,
            TwilioProgrammableChatError::ErrorCode50101 => None,
            TwilioProgrammableChatError::ErrorCode50332 => None,
            TwilioProgrammableChatError::ErrorCode50393 => None,
            TwilioProgrammableChatError::ErrorCode50436 => Some(r#"There is a limit to how many participants can be active in the same conversation at once. Adding this participant would exceed that limit."#),
            TwilioProgrammableChatError::ErrorCode50374 => Some(r#"'State' field can't be removed or set to empty if it was already set before."#),
            TwilioProgrammableChatError::ErrorCode50330 => None,
            TwilioProgrammableChatError::ErrorCode50382 => Some(r#"You are trying to set 'TimeToInactive' and/or 'TimeToClosed' without 'State' parameter in request during conversation creation"#),
            TwilioProgrammableChatError::ErrorCode50418 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50378 => Some(r#"'State' parameter value is set to some not supported value. Supported values are 'active', 'inactive', 'closed'."#),
            TwilioProgrammableChatError::ErrorCode50438 => Some(r#"There is an existing group conversation with the same participant list."#),
            TwilioProgrammableChatError::ErrorCode50107 => None,
            TwilioProgrammableChatError::ErrorCode50201 => None,
            TwilioProgrammableChatError::ErrorCode50328 => None,
            TwilioProgrammableChatError::ErrorCode50104 => None,
            TwilioProgrammableChatError::ErrorCode50309 => Some(r#"## Error - 50309

### Programmable Chat: Invalid Date Updated parameter

#### Possible Causes 
*  Request does not contain correctly formatted parameter for Date Updated.

#### Possible Solutions
*  Confirm a valid Date Updated parameter is passed in request. "#),
            TwilioProgrammableChatError::ErrorCode50363 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50414 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50310 => None,
            TwilioProgrammableChatError::ErrorCode50371 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50373 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50442 => Some(r#"The conversation participant being updated does not have a projected address."#),
            TwilioProgrammableChatError::ErrorCode50370 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50511 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50327 => None,
            TwilioProgrammableChatError::ErrorCode50211 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50602 => None,
            TwilioProgrammableChatError::ErrorCode50437 => Some(r#"A participant matching this one already exists in the conversation."#),
            TwilioProgrammableChatError::ErrorCode50051 => None,
            TwilioProgrammableChatError::ErrorCode50408 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50440 => Some(r#"The conversation participant being updated does not have a proxy address."#),
            TwilioProgrammableChatError::ErrorCode50351 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50213 => Some(r#"The requested user is already being added or removed from this service instance concurrently with another API request. The last request will be rejected to avoid inconsistent state."#),
            TwilioProgrammableChatError::ErrorCode50100 => None,
            TwilioProgrammableChatError::ErrorCode50369 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50516 => Some(r#"Not a number string was provided as message index."#),
            TwilioProgrammableChatError::ErrorCode50204 => None,
            TwilioProgrammableChatError::ErrorCode50416 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50053 => None,
            TwilioProgrammableChatError::ErrorCode50513 => Some(r#"Author identity or address not found among Group MMS participants."#),
            TwilioProgrammableChatError::ErrorCode50419 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50413 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50362 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50320 => None,
            TwilioProgrammableChatError::ErrorCode50202 => None,
            TwilioProgrammableChatError::ErrorCode50105 => None,
            TwilioProgrammableChatError::ErrorCode50058 => None,
            TwilioProgrammableChatError::ErrorCode50422 => None,
            TwilioProgrammableChatError::ErrorCode50003 => None,
            TwilioProgrammableChatError::ErrorCode50324 => None,
            TwilioProgrammableChatError::ErrorCode50421 => None,
            TwilioProgrammableChatError::ErrorCode50361 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50364 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50415 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50212 => None,
            TwilioProgrammableChatError::ErrorCode50600 => None,
            TwilioProgrammableChatError::ErrorCode50203 => None,
            TwilioProgrammableChatError::ErrorCode50056 => None,
            TwilioProgrammableChatError::ErrorCode50403 => None,
            TwilioProgrammableChatError::ErrorCode50420 => None,
            TwilioProgrammableChatError::ErrorCode50321 => None,
            TwilioProgrammableChatError::ErrorCode50502 => None,
            TwilioProgrammableChatError::ErrorCode19038 => None,
            TwilioProgrammableChatError::ErrorCode50401 => None,
            TwilioProgrammableChatError::ErrorCode50507 => None,
            TwilioProgrammableChatError::ErrorCode50206 => None,
            TwilioProgrammableChatError::ErrorCode50435 => Some(r#"The conversation's Group MMS could not be activated."#),
            TwilioProgrammableChatError::ErrorCode50303 => None,
            TwilioProgrammableChatError::ErrorCode50078 => None,
            TwilioProgrammableChatError::ErrorCode50379 => Some(r#"'TimeToInactive' parameter supports values which are ISO8601 durations."#),
            TwilioProgrammableChatError::ErrorCode50350 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50060 => None,
            TwilioProgrammableChatError::ErrorCode50331 => None,
            TwilioProgrammableChatError::ErrorCode50329 => None,
            TwilioProgrammableChatError::ErrorCode50441 => Some(r#"You cannot add a proxy address to the participant."#),
            TwilioProgrammableChatError::ErrorCode50391 => Some(r#"The requested conversation is already being added or removed from this service instance concurrently with another API request. The last request will be rejected to avoid inconsistent state."#),
            TwilioProgrammableChatError::ErrorCode50106 => None,
            TwilioProgrammableChatError::ErrorCode50368 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50214 => None,
            TwilioProgrammableChatError::ErrorCode50512 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50326 => None,
            TwilioProgrammableChatError::ErrorCode50405 => None,
            TwilioProgrammableChatError::ErrorCode50006 => Some(r#"Invalid Account SID"#),
            TwilioProgrammableChatError::ErrorCode50209 => None,
            TwilioProgrammableChatError::ErrorCode50306 => None,
            TwilioProgrammableChatError::ErrorCode50508 => None,
            TwilioProgrammableChatError::ErrorCode20161 => Some(r#"Update request doesn't contain any parameters"#),
            TwilioProgrammableChatError::ErrorCode50400 => None,
            TwilioProgrammableChatError::ErrorCode50341 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50407 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50433 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50200 => None,
            TwilioProgrammableChatError::ErrorCode50402 => None,
            TwilioProgrammableChatError::ErrorCode50432 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50367 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50055 => None,
            TwilioProgrammableChatError::ErrorCode50061 => None,
            TwilioProgrammableChatError::ErrorCode50004 => None,
            TwilioProgrammableChatError::ErrorCode50610 => None,
            TwilioProgrammableChatError::ErrorCode50305 => None,
            TwilioProgrammableChatError::ErrorCode50322 => None,
            TwilioProgrammableChatError::ErrorCode50334 => None,
            TwilioProgrammableChatError::ErrorCode50406 => None,
            TwilioProgrammableChatError::ErrorCode50050 => None,
            TwilioProgrammableChatError::ErrorCode50349 => Some(r#"The requested channel is already being added or removed from this service instance concurrently with another API request. The last request will be rejected to avoid inconsistent state."#),
            TwilioProgrammableChatError::ErrorCode50503 => None,
            TwilioProgrammableChatError::ErrorCode50109 => None,
            TwilioProgrammableChatError::ErrorCode50065 => None,
            TwilioProgrammableChatError::ErrorCode50443 => Some(r#"The conversation participant being updated can not have a projected address."#),
            TwilioProgrammableChatError::ErrorCode50342 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50076 => Some(r#"Programmable Chat: Webhook failed to execute successfully due to timeout"#),
            TwilioProgrammableChatError::ErrorCode50390 => None,
            TwilioProgrammableChatError::ErrorCode50376 => Some(r#"'TimeToClosed' duration should be greater or equal to 10 minutes."#),
            TwilioProgrammableChatError::ErrorCode50366 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50392 => Some(r#"'PreWebhookTimeout' should be greater than 0ms."#),
            TwilioProgrammableChatError::ErrorCode50500 => None,
            TwilioProgrammableChatError::ErrorCode50002 => None,
            TwilioProgrammableChatError::ErrorCode50308 => None,
            TwilioProgrammableChatError::ErrorCode50103 => None,
            TwilioProgrammableChatError::ErrorCode50504 => Some(r#"## Error - 50504

### Programmable Chat: Message body parameter is too long"#),
            TwilioProgrammableChatError::ErrorCode50307 => None,
            TwilioProgrammableChatError::ErrorCode50300 => None,
            TwilioProgrammableChatError::ErrorCode50409 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50325 => None,
            TwilioProgrammableChatError::ErrorCode50404 => None,
            TwilioProgrammableChatError::ErrorCode50323 => None,
            TwilioProgrammableChatError::ErrorCode50063 => None,
            TwilioProgrammableChatError::ErrorCode50360 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50444 => Some(r#"The conversation participant being updated can not have an identity."#),
            TwilioProgrammableChatError::ErrorCode50302 => None,
            TwilioProgrammableChatError::ErrorCode50102 => None,
            TwilioProgrammableChatError::ErrorCode50411 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50372 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50430 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50000 => None,
            TwilioProgrammableChatError::ErrorCode50601 => None,
            TwilioProgrammableChatError::ErrorCode50439 => Some(r#"Address used as Projected Address does not belong to the account."#),
            TwilioProgrammableChatError::ErrorCode50510 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50347 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50210 => None,
            TwilioProgrammableChatError::ErrorCode50501 => None,
            TwilioProgrammableChatError::ErrorCode50001 => None,
            TwilioProgrammableChatError::ErrorCode50505 => None,
            TwilioProgrammableChatError::ErrorCode50365 => Some(r#"null"#),
            TwilioProgrammableChatError::ErrorCode50301 => None,
            TwilioProgrammableChatError::ErrorCode50385 => Some(r#"Conversations features do not function in the region you've selected. The API will return this error to indicate that, preventing further activity."#)
        }
    }
}
